### ISSUE TITLE
"should not attempt to tweak an array"

### ISSUE THREAD

**Issue by miles-po** [graphile/postgraphile#1110]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.4.1

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE array_test (
  some_array text[]
);
INSERT INTO array_test VALUES ('{one,two,three}'::text[]);
```

Steps to reproduce:

1. `npx postgraphile -c "postgres://user:password@localhost/db"`

2. Make a GraphQL query from a table, including an array column.

```graphql
{
  allArrayTests {
    nodes {
      someArray
    }
  }
}
```

Current behavior:
Query works as expected, but an exception is thrown and logged on the console on every query.

```
Error: Internal graphile-build-pg error: should not attempt to tweak an array, please process array before tweaking (type: "pg_catalog._text")
    at pgTweakFragmentForTypeAndModifier (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:265:23)
    at pgTweakFragmentForTypeAndModifier (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgTypesPlugin.js:263:16)
    at Object.getSelectValueForFieldAndTypeAndModifier (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgColumnsPlugin.js:47:18)
    at Array.pgQuery (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgColumnsPlugin.js:110:37)
    at Object.<anonymous> (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/queryFromResolveDataFactory.js:52:17)
    at queryBuilder.select (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/pgField.js:44:27)
    at callIfNecessary (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:22:12)
    at QueryBuilder.lock (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:650:22)
    at QueryBuilder.lockEverything (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:721:10)
    at QueryBuilder.build (/Users/mileselam/.npm/_npx/91656/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:549:10)
```

The immediately preceding log line begins:
```
0 error(s) in 91.55ms :: query IntrospectionQuery {
```

Expected behavior:
No exception. (Exceptions are expensive performance-wise.)

**Comment by benjie** [comment]
I'm afraid I cannot reproduce this issue; please can you provide additional information about your setup?

![Screenshot 2019-06-29 15 17 46](https://user-images.githubusercontent.com/129910/60385447-10832680-9a81-11e9-837e-92d16a6dd01d.png)

![Screenshot 2019-06-29 15 18 22](https://user-images.githubusercontent.com/129910/60385457-2bee3180-9a81-11e9-934d-6c03958e4656.png)

**Comment by miles-po** [comment]
Ah, sorry, I messed up my test. I forgot to include the important part. Yes, you are correct that just an array column won't trigger an error. But a *domain* that is a text array underneath with. I will update the test case to match.

Again, sorry for the oversight, and thank you for responding so quickly.

**Comment by miles-po** [comment]
I just double-checked the domain and non-domain cases. Non-domain text[] works as expected—what you have seen. As a domain type, it throws the exception, presumably because it doesn't recognize base types of domains.

Perhaps check the typbasetype column in pg_type? Here's the pg_type entry for `test_domain` on my system for reference.

```json
{
    "typacl": null,
    "typlen": -1,
    "typelem": "0",
    "typname": "test_domain",
    "typsend": "array_send",
    "typtype": "d",
    "typalign": "i",
    "typarray": "0",
    "typbyval": false,
    "typdelim": ",",
    "typinput": "domain_in",
    "typmodin": "-",
    "typndims": 1,
    "typowner": "10",
    "typrelid": "0",
    "typmodout": "-",
    "typoutput": "array_out",
    "typtypmod": -1,
    "typanalyze": "array_typanalyze",
    "typdefault": null,
    "typnotnull": false,
    "typreceive": "domain_recv",
    "typstorage": "x",
    "typbasetype": "1009",
    "typcategory": "A",
    "typcollation": "100",
    "typisdefined": true,
    "typnamespace": "2200",
    "typdefaultbin": null,
    "typispreferred": false
}
```
typbasetype of 1009 is of course text[].
