### ISSUE TITLE
pg-pubsub plugin with docker-compose

### ISSUE THREAD

**Issue by ohlr** [graphile/postgraphile#1150]
I'm submitting a ... 

* [x] bug report

I try to implement pub/sub as described [here](https://www.graphile.org/postgraphile/subscriptions/#simple-subscriptions) but with DockerCompose.

To reproduce you can use this github [repo](https://github.com/alexisrolland/docker-postgresql-postgraphile) together with the changes below.

Steps to reproduce:

## Dockerfile
```
FROM node:alpine
LABEL description="Instant high-performance GraphQL API for your PostgreSQL database https://github.com/graphile/postgraphile"

RUN npm install -g postgraphile
RUN npm install -g postgraphile-plugin-connection-filter
RUN npm install -g @graphile/pg-pubsub

EXPOSE 5000
ENTRYPOINT ["postgraphile", "-n", "0.0.0.0"]
```
Added `RUN npm install -g @graphile/pg-pubsub`

## Docker-Compose File
```
    command: [
      "postgraphile",
      "--plugins", "@graphile/pg-pubsub",
      "--subscriptions",
      "--simple-subscriptions",
      "--connection", "${DATABASE_URL}",
      "--port", "5433",
      "--schema", "my_schema",
      "--append-plugins", "postgraphile-plugin-connection-filter"
    ]
```
Added `plugins, subscriptions, simple-subscriptions`

## Error Message:
```

my-graphql | /usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js:166
my-graphql |     throw new Error(`--plugins must be the first argument to postgraphile if specified`);
my-graphql |     ^
my-graphql | 
my-graphql | Error: --plugins must be the first argument to postgraphile if specified
my-graphql |     at Object.<anonymous> (/usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js:166:11)
my-graphql |     at Module._compile (internal/modules/cjs/loader.js:936:30)
my-graphql |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
my-graphql |     at Module.load (internal/modules/cjs/loader.js:790:32)
my-graphql |     at Function.Module._load (internal/modules/cjs/loader.js:703:12)
my-graphql |     at Module.require (internal/modules/cjs/loader.js:830:19)
my-graphql |     at require (internal/modules/cjs/helpers.js:68:18)
my-graphql |     at Object.<anonymous> (/usr/local/lib/node_modules/postgraphile/cli.js:9:20)
my-graphql |     at Module._compile (internal/modules/cjs/loader.js:936:30)
my-graphql |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
```

**Comment by benjie** [comment]
I'm not sufficiently knowledgeable in docker-compose to help much here (that doesn't look like a full docker compose file?); but it seems to me that `--plugins` is not being passed as the first argument to `postgraphile`; could this be because of the entrypoint containing `-n 0.0.0.0`? Maybe try changing the entrypoint so that `--plugins` appears there before the `"-n"` flag?

**Comment by benjie** [comment]
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).

**Comment by ohlr** [comment]
@benjie you were right with the `-n 0.0.0.0` now it works. Thanks for your help.

One more thing though:

Using:
```
FROM graphile/postgraphile
RUN yarn add @graphile/pg-pubsub
```
as dockerfile yields a similar error:

```
graphql-server_1      | /postgraphile/build-turbo/postgraphile/cli.js:166
graphql-server_1      |     throw new Error(`--plugins must be the first argument to postgraphile if specified`);
```
Any way to avoid this with the provided image?

**Comment by benjie** [comment]
Can you supply the Docker command-line you're using? I've not got Docker handy but I'd expect it to work so long as `--plugins` is the first argument passed.

**Comment by ohlr** [comment]
I am using `docker-compose up`. From `docker-compose ps` I see that it uses `./cli.js postgraphile --plugins ...` internally. 

```
version: '3.1'
services:
  db:
    container_name: my-db
    restart: always
    image: my-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - default
    ports:
      - 5432:5432

  graphql:
    container_name: my-graphql
    restart: always
    image: my-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5433:5433
    command: [
      "postgraphile",
      "--plugins", "@graphile/pg-pubsub",
      "--subscriptions",
      "--simple-subscriptions",
      "--connection", "${DATABASE_URL}",
      "--port", "5433",
      "-n", "0.0.0.0",
      "--schema", "my_schema",
      "--append-plugins", "postgraphile-plugin-connection-filter"
    ]

networks:
    network:

volumes:
    db:
```
modified from https://github.com/alexisrolland/docker-postgresql-postgraphile

**Comment by benjie** [comment]
Ah; try removing `"postgraphile"` from the command.

**Comment by ohlr** [comment]
Thanks!
