### ISSUE TITLE
4.5.0.rc1 Docker image crashing with TypeError: Cannot read property 'CLASS' of undefined

### ISSUE THREAD

**Issue by lukepatrick** [graphile/postgraphile#1186]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

docker container `graphile/postgraphile:v4.5.0-rc.1`

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

Using the docker base image from graphile, I've installed a few plugins, start up the container and get exceptions causing the app to crash.

My docker file example:

```
FROM graphile/postgraphile:v4.5.0-rc.1

RUN npm install graphile-build-pg graphql pg

RUN yarn add postgraphile-plugin-connection-filter@1.0.0-beta.23
RUN yarn add @_lukepatrick/postgraphile-upsert-plugin@1.5.0
RUN yarn add postgraphile-plugin-nested-mutations@1.0.0-alpha.23

ENTRYPOINT [ "/bin/bash", "-c", "./cli.js -n 0.0.0.0 -s foobar --jwt-token-identifier secret --jwt-secret ${JWT_SECRET} --default-role foo --watch --enhance-graphiql --allow-explain --append-plugins postgraphile-plugin-connection-filter,@_lukepatrick/postgraphile-upsert-plugin:PgMutationUpsertPlugin,postgraphile-plugin-nested-mutations ${ARGS}" ]
```

after container startup, in the logs:
```
TypeError: Cannot read property 'CLASS' of undefined
    at Object.<anonymous> (/postgraphile/node_modules/graphile-utils/node8plus/makePgSmartTagsPlugin.js:8:39)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/postgraphile/node_modules/graphile-utils/node8plus/index.js:24:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
/postgraphile/node_modules/graphile-utils/node8plus/makePgSmartTagsPlugin.js:8
    [graphile_build_pg_1.PgEntityKind.CLASS]: "for tables, composite types, views and materialized views",
```

No issues when using a 4.4 base, e.g `FROM graphile/postgraphile:v4`

**Comment by benjie** [comment]
Your Dockerfile is explicitly adding an old version of `graphile-build-pg`; thatmight be the issue. `graphile-build-pg` is bundled; you need to use the same version that PostGraphile itself bundles. I'd also recommend using `yarn` consistently.

**Comment by lukepatrick** [comment]
got it, didn't realize `graphile-build-pg` was packaged in. removing that fixed the issue.

**Comment by benjie** [comment]
Thanks for letting me know
