### ISSUE TITLE
Supports peer authentication(?)

### ISSUE THREAD

**Issue by odinho** [graphile/postgraphile#1197]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.5.0

**Steps to reproduce:**
```
odin@kaa:~/tmp/postgraphile$ sudo grep '^[^#]' /etc/postgresql/10/main/pg_hba.conf 
local   all             postgres                                peer
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
odin@kaa:~/tmp/postgraphile$ echo 'SELECT name FROM strategies LIMIT 1;' | psql odin
Pager usage is off.
Expanded display is used automatically.
  name   
---------
 default
(1 row)

odin@kaa:~/tmp/postgraphile$ postgraphile -c odin
```

**Current behavior:**
```
odin@kaa:~/tmp/postgraphile$ postgraphile -c odin

PostGraphile v4.5.0 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql (enhance with '--enhance-graphiql')
  ‣ Postgres connection: postgres:///odin
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Join Michel Pelletier in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

error: password authentication failed for user "odin"
    at Connection.parseE (/home/odin/tmp/postgraphile/node_modules/pg/lib/connection.js:606:11)
    at Connection.parseMessage (/home/odin/tmp/postgraphile/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/home/odin/tmp/postgraphile/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Expected behavior:**

Either:
- It working, or
- Documented somewhere that peer authentication (ident) doesn't work

**Comment by benjie** [comment]
Peer authentication works for me on Linux and Mac.

Your error implies that your environment is attempting password authentication; do you have the `PGPASS` envvar set?

**Comment by odinho** [comment]
Wow, that was insanely quick. I've been playing around in the mean time (I set a password to get further) :)

I don't have that in my env no. I've found out it's the node pg bindings that seem to be the problem, for some reason. Look:

```
$ node
> pg = require("pg")
> c = new pg.Client(); c.connect(); c.query('SELECT * FROM strategies LIMIT 1', (_, res) => console.log(res))
undefined
> (node:17176) UnhandledPromiseRejectionWarning: error: password authentication failed for user "odin"
    at Connection.parseE (/home/odin/tmp/postgraphile/node_modules/pg/lib/connection.js:606:11)
    ...
```

Whereas psql works:
```
$ psql --quiet
odin=# 
```
And Python works:
```
$ python
>>> import psycopg2
>>> conn = psycopg2.connect("dbname=odin"); cur = conn.cursor(); cur.execute("SELECT name FROM strategies"); cur.fetchone()
('default',)

```

**Comment by benjie** [comment]
🤷‍♂️ try setting PGHOST=“/path/to/postgres.sock” (on mobile so can’t check location; think it’s in /var/run somewhere?)

**Comment by odinho** [comment]
That works. `$ PGHOST=/run/postgresql/ postgraphile -c fk` :man_shrugging:

**Comment by odinho** [comment]
It's very unfortunate, but `node-postgres` doesn't support this. They've used `localhost` as the default unlike every other postgres client, making this behaviour most surprising.

https://github.com/brianc/node-postgres/issues/1493 -- so certainly not a bug with `postgraphile`. :)

**Comment by benjie** [comment]
When I moved to Linux I had to set this in my bash profile, to make peer auth work in the same way on Linux as it was previously working on Mac:

```
export PGHOST='/var/run/postgresql'
```
