### ISSUE TITLE
utf8 characters is not supported for enum option

### ISSUE THREAD

**Issue by selegiline** [graphile/postgraphile#1206]
I'm submitting a ... 

* [ ] bug report
* [v ] feature request
* [ ] question 

PostGraphile version:

Minimal SQL file that can be loaded into a clean database:

```sql
create type notice_type 	as enum ('通知', '消息', '待办');
```

Steps to reproduce:

Current behavior:
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
    at assertValidSchema (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\validate.js:71:11)
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\validation\validate.js:54:35)
    at parseQuery (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:254:48)
    at Promise.all.paramsList.map (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:547:63)
    at Array.map (<anonymous>)
    at requestHandler (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:510:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
    at assertValidSchema (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\type\validate.js:71:11)
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\node_modules\graphql\validation\validate.js:54:35)
    at parseQuery (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:254:48)
    at Promise.all.paramsList.map (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:547:63)
    at Array.map (<anonymous>)
    at requestHandler (C:\Users\Administrator\AppData\Roaming\npm\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:510:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Expected behavior:
the convention  of /^[_a-zA-Z][_a-zA-Z0-9]*$/ is ok to name table /column/ function ......   but restrict too much for an enum value

**Comment by benjie** [comment]
Hi @selegiline you can solve this with an enum inflector. Enums must ultimately respect the regexp given (as required by the GraphQL spec) but you could use an inflector to translate your enum values to GraphQL.


[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).
