### ISSUE TITLE
oldInflector looks to be the new one

### ISSUE THREAD

**Issue by jammo-nl** [graphile/postgraphile#1244]
On https://www.graphile.org/postgraphile/make-add-inflectors-plugin/ it says:

"if you need to call the previous inflector you're replacing then you can pass 
an "inflectors generator" function which will be passed the old inflectors you 
can then call into."

If we try to use the following plugin: 

```
const { makeAddInflectorsPlugin } = require('graphile-utils');

module.exports = makeAddInflectorsPlugin(
        oldInflection => ({
                pluralize(str) {
                        console.log('pluralizing: ' + str);
                        if (str.match(/^trans$/i)) {
                                return str + 'es';
                        }
                        return oldInflection.pluralize.call(this, str);
                        //return oldInflection.pluralize(str);
                },
                singularize(str) {
                        console.log('singularizing: ' + str);
                        if (str.match(/^transes$/i)) {
                                return str.substr(0, 5);
                        }
                        return oldInflection.singularize.call(this, str);
                        //return oldInflection.singularize(str);
                }
        }),
        true
);
```

then postgraphile doesn't start, showing:

... (long list of repeating the following line)
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
pluralizing: BktAnnouncementItem
A serious error occurred when building the initial schema. Exiting because 
`retryOnInitFail` is not set. Error details:

RangeError: Maximum call stack size exceeded
    at WriteStream.getColorDepth (internal/tty.js:181:22)
    at Object.Console.<computed> (internal/console/constructor.js:256:16)
    at Object.Console.<computed> (internal/console/constructor.js:271:40)
    at Object.log (internal/console/constructor.js:282:61)
    at Object.pluralize (/home/postgraphile/MyInflectorPlugin.js:15:12)
    at Object.pluralize (/home/postgraphile/MyInflectorPlugin.js:19:35)
    at Object.pluralize (/home/postgraphile/MyInflectorPlugin.js:19:35)
    at Object.pluralize (/home/postgraphile/MyInflectorPlugin.js:19:35)
    at Object.pluralize (/home/postgraphile/MyInflectorPlugin.js:19:35)
    at Object.pluralize (/home/postgraphile/MyInflectorPlugin.js:19:35)

it looks like inside our new function, the oldInflection in fact is the newly 
defined one, instead of the old one, thus resulting in an endless loop

**Comment by benjie** [comment]
Yes, you need to store the methods that you're overwriting otherwise you're calling yourself. For example:

```js
const { makeAddInflectorsPlugin } = require('graphile-utils');

module.exports = makeAddInflectorsPlugin(
        ({pluralize, singularize}) => ({
                pluralize(str) {
                        if (str.match(/^trans$/i)) {
                                return str + 'es';
                        }
                        return pluralize.call(this, str);
                },
                singularize(str) {
                        if (str.match(/^transes$/i)) {
                                return str.substr(0, 5);
                        }
                        return singularize.call(this, str);
                }
        }),
        true
);
```

**Comment by benjie** [comment]
[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).
