### ISSUE TITLE
Setting queryCacheMaxSize to 0 throws an error

### ISSUE THREAD

**Issue by zacherkkila** [graphile/postgraphile#1311]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

`"postgraphile": "^4.5.5"`

Current behavior:

App crashes when setting `queryCacheMaxSize` to 0

I am currently diagnosing a memory issue that happens when I call a rather large mutation for a custom function (~30kb query string length but I assume in memory it is considerably larger than the cache estimate) every 30 seconds and was trying to disable the cache to make sure this isn't the root cause as mentioned in #851

The documentation states:

`queryCacheMaxSize: Max query cache size in bytes (extremely approximate, not accurate at all). Default 50000000 (~50MB). Set to 0 to disable.`

However setting this like below

```
const options: PostGraphileOptions<Request, Response> = {
    ...
    queryCacheMaxSize:0,
```

Produces the following error on startup

```
2020-07-15T13:43:15.338029+00:00 app[web.1]: Fatal error occurred starting server!
2020-07-15T13:43:15.340069+00:00 app[web.1]: Error: Max length must be >= 2
2020-07-15T13:43:15.340070+00:00 app[web.1]: at new LRU (/app/node_modules/@graphile/lru/node8plus/index.js:9:19)
2020-07-15T13:43:15.340071+00:00 app[web.1]: at Object.createPostGraphileHttpRequestHandler [as default] (/app/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:222:24)
2020-07-15T13:43:15.340071+00:00 app[web.1]: at Object.postgraphile (/app/node_modules/postgraphile/build/postgraphile/postgraphile.js:165:58)
2020-07-15T13:43:15.340072+00:00 app[web.1]: at Object.installPostGraphile (/app/@app/server/dist/middleware/installPostGraphile.js:213:39)
2020-07-15T13:43:15.340072+00:00 app[web.1]: at Object.makeApp (/app/@app/server/dist/app.js:75:22)
2020-07-15T13:43:15.340072+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-15T13:43:15.340073+00:00 app[web.1]: at async main (/app/@app/server/dist/index.js:15:17)
2020-07-15T13:43:15.383531+00:00 app[web.1]: error Command failed with exit code 101.
2020-07-15T13:43:15.383710+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Setting to 2MB as below

```
const options: PostGraphileOptions<Request, Response> = {
    ...
    queryCacheMaxSize:2000000,
```

Seems to help quite a bit so far but time will tell if that fixed it completely or is just increasing slower. I figured I would log this issue either way as the docs claim setting to 0 will work to disable the query cache and I would like to try it if I am still getting memory issues

Expected behavior:

Cache is disabled

**Comment by benjie** [comment]
Good spot; this must have been an issue from when we switched to using `@graphile/lru`. We have code that prevents caching being used if max size <= 0, but we still _create_ the cache, and that's what's causing the issue.

https://github.com/graphile/postgraphile/blob/8a0c6a8a68797f94f58eda48dc20f03405ebe000/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L345

https://github.com/graphile/postgraphile/blob/8a0c6a8a68797f94f58eda48dc20f03405ebe000/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L326

PR welcome to fix this; ensure it's opened against the v4 branch.
