### ISSUE TITLE
[BUG] Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [graphile/postgraphile#1335]
I not use any graphql package except `postgraphile`
---

Version: `"postgraphile": "^4.8.0"`

package.json
```json
{
  "dependencies": {
    "postgraphile": "^4.8.0",
    "express": "^4.17.1",
    "bufferutil": "^4.0.1",
    "utf-8-validate": "^5.0.2",
    "pg-native": "^3.0.0"
  }
}
```

server.js
```javascript
const express = require('express')
const {postgraphile} = require('postgraphile')

const app = express()

const POSTGRES_URL = `postgres://postgres:pass@localhost:5432/rollme`
const API_GRAPHQL_PORT = 3000

app.use(
  postgraphile(POSTGRES_URL, 'public', {
    watchPg: true,
    graphiql: true,
    enhanceGraphiql: true,
  })
);

app.listen(API_GRAPHQL_PORT, () => {
  console.log(`Server listening at ${API_GRAPHQL_PORT}`)
});
```

output
```cmd
$ node server.js
Server listening at 3000
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (C:\localhost\rollme\api\node_modules\postgraphile\node_modules\graphql\jsutils\instanceOf.js:28:13)
    at isSchema (C:\localhost\rollme\api\node_modules\postgraphile\node_modules\graphql\type\schema.js:36:34)
    at assertSchema (C:\localhost\rollme\api\node_modules\postgraphile\node_modules\graphql\type\schema.js:40:8)
    at validateSchema (C:\localhost\rollme\api\node_modules\postgraphile\node_modules\graphql\type\validate.js:44:28)
    at assertValidSchema (C:\localhost\rollme\api\node_modules\postgraphile\node_modules\graphql\type\validate.js:68:16)
    at Object.validate (C:\localhost\rollme\api\node_modules\postgraphile\node_modules\graphql\validation\validate.js:54:35)
    at parseQuery (C:\localhost\rollme\api\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:258:48)
    at C:\localhost\rollme\api\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:551:63
    at Array.map (<anonymous>)
    at requestHandler (C:\localhost\rollme\api\node_modules\postgraphile\build\postgraphile\http\createPostGraphileHttpRequestHandler.js:514:
52)

```

**Comment by benjie** [comment]
You can use webpack, you just have to set it up very carefully - see: https://github.com/graphile/postgraphile-lambda-example
