### ISSUE TITLE
Missing 'assets' directory after yarn install or add - Error: Cannot find module '../../assets/favicon.ico'

### ISSUE THREAD

**Issue by jsauca** [graphile/postgraphile#1378]
After I run "yarn install" or "yarn add {any_module}" then run "yarn dev" I am facing the following issue:

```
Error: Cannot find module '../../assets/favicon.ico'
Require stack:
- /Users/{username}/Documents/GitHub/{my_project}/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js
- /Users/{username}/Documents/GitHub/{my_project}/node_modules/postgraphile/build/postgraphile/postgraphile.js
- /Users/{username}/Documents/GitHub/{my_project}/node_modules/postgraphile/build/postgraphile/index.js
- /Users/{username}/Documents/GitHub/{my_project}/node_modules/postgraphile/build/index.js
- /Users/{username}/Documents/GitHub/{my_project}/node_modules/postgraphile/index.js
- /Users/{username}/Documents/GitHub/{my_project}/dist/private/memory/server.js
- /Users/{username}/Documents/GitHub/{my_project}/node_modules/webpack-hot-server-middleware/src/index.js
- /Users/{username}/Documents/GitHub/{my_project}/server/middlewares/middlewareDevelopment.js
- /Users/{username}/Documents/GitHub/{my_project}/server/server.js
    at Function.Module._resolveFilename **(internal/modules/cjs/loader.js:880:15)**
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/{username}/Documents/GitHub/{my_project}/node_modules/postgraphile/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts:47:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/Users/{username}/Documents/GitHub/{my_project}/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/Users/{username}/Documents/GitHub/{my_project}/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

The only way I have found to avoid this error is to run "npm install" after running "yarn add {any_module}" or yarn install.
Then I can run "yarn dev" without any issues. 

I have looked into my node_modules/postgraphile/build folder; I can see that 'assets' folder is missing after running yarn install. However; "assets" is present after running npm install!

See screenshots attached..

**After yarn install - missing "assets" directory**
<img width="303" alt="yarn_install" src="https://user-images.githubusercontent.com/29192645/97764535-0f757400-1b63-11eb-8de3-43015b7aad68.png">

**After npm install - all good!**
<img width="329" alt="npm_install" src="https://user-images.githubusercontent.com/29192645/97764544-13a19180-1b63-11eb-8359-3412c73ef79b.png">
 
I am working with the following:
- Postgraphile 4.9.2
- Node v14.14.0
- Express 4.17.1,
- Webpack 4.44.2
I have clean the cache, downgraded / upgraded packages, modules, yarn, node and so on but error is still here!

This error might relates to  https://github.com/graphile/postgraphile/issues/6 ??

Thanks for your help!

**Comment by jsauca** [comment]
.yarnclean was deleting the assets folder.... 😆😆
