### ISSUE TITLE
subscriptionAuthorizationFunction doesn't run when the connection is established

### ISSUE THREAD

**Issue by UchihaVeha** [graphile/postgraphile#1379]
Subscription establish WebSocket connection and return data even if secure function always raise an error, no any errors in the console

```
const common = {
  pluginHook: makePluginHook([PgPubsub]),
  appendPlugins: [PgManyToManyPlugin, ConnectionFilterPlugin, SessionPlugin],
  graphileBuildOptions: {
    connectionFilterRelations: true,
  },
  subscriptions: true,
  simpleSubscriptions: true,
  subscriptionAuthorizationFunction: 'private.validate_subscription',
};

const dev = {
  ...common,
  retryOnInitFail: true,
  watchPg: true,
  dynamicJson: true,
  setofFunctionsContainNulls: false,
  ignoreRBAC: false,
  ignoreIndexes: true,
  showErrorStack: 'json' as const,
  extendedErrors: ['hint', 'detail', 'errcode'],
  exportGqlSchemaPath: 'schema.graphql',
  graphiql: true,
  enhanceGraphiql: true,
  ownerConnectionString: 'postgres://postgres:postgres@localhost:5450/postgres',
  allowExplain() {
    // TODO: customise condition!
    return true;
  },
  enableQueryBatching: true,
  legacyRelations: 'omit' as const,
  // pgSettings(req) {
  //   /* TODO */
  // },
  jwtSecret: process.env.JWT_SECRET,
  jwtPgTypeIdentifier: 'public.jwt_token',
};
```

```
CREATE FUNCTION private.validate_subscription(topic text)
RETURNS TEXT AS $$
BEGIN
   RAISE EXCEPTION 'topic: %', topic;
END;
$$ LANGUAGE plpgsql VOLATILE SECURITY DEFINER;
```

```
"@graphile/pg-pubsub": "^4.9.0",
 "postgraphile": "^4.9.2"
```

**Comment by benjie** [comment]
Attempt to reproduce 1:

```
benjie@Benjie-Box:~/Dev/graphile/graphile-engine$ createdb issue1379
benjie@Benjie-Box:~/Dev/graphile/graphile-engine$ psql issue1379
psql (11.9 (Ubuntu 11.9-1.pgdg18.04+1))
Type "help" for help.

[issue1379] # create schema private;
CREATE SCHEMA
Time: 5.180 ms
[issue1379] # CREATE FUNCTION private.validate_subscription(topic text)
... # RETURNS TEXT AS $$
... # BEGIN
... #    RAISE EXCEPTION 'topic: %', topic;
... # END;
... # $$ LANGUAGE plpgsql VOLATILE SECURITY DEFINER;
CREATE FUNCTION
Time: 9.928 ms
[issue1379] # \q
benjie@Benjie-Box:~/Dev/graphile/graphile-engine$ cd postgraphile/
benjie@Benjie-Box:~/Dev/graphile/graphile-engine/postgraphile$ ./rmlocal.sh 
benjie@Benjie-Box:~/Dev/graphile/graphile-engine/postgraphile$ node build/postgraphile/cli.js --plugins @graphile/pg-pubsub -c issue1379 --simple-subscriptions --subscriptions                                                                              

PostGraphile v4.9.2 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql (subscriptions enabled)
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql
  ‣ Postgres connection: postgres:///issue1379
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/

* * *

WARNING: there were no matches for makePgSmartTagsPlugin rule 0 - {
  kind: 'class',
  match: 'model.a_child1',
  tags: { foreignKey: '(a_id) references model.a_base (id)' },
  description: 'DEFINITELY LOADED 6'
}
^Cbenjie@Benjie-Box:~/Dev/graphile/graphile-engine/postgraphile$ node build/postgraphile/cli.js --plugins @graphile/pg-pubsub -c issue1379 --simple-subscriptions --subscriptions --subscription-authorization-function 'private.validate_subscription'

PostGraphile v4.9.2 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql (subscriptions enabled)
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql
  ‣ Postgres connection: postgres:///issue1379
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/

* * *

WARNING: there were no matches for makePgSmartTagsPlugin rule 0 - {
  kind: 'class',
  match: 'model.a_child1',
  tags: { foreignKey: '(a_id) references model.a_base (id)' },
  description: 'DEFINITELY LOADED 6'
}
0 error(s) in 23.27ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
```

Operation:

```
subscription {
  listen(topic:"anything") {
    query {
      __typename
    }
  }
}
```

Result:

```
{
  "errors": [
    {
      "message": "topic: postgraphile:anything",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listen"
      ]
    }
  ]
}
```

So this definitely works with the CLI; so it absolutely should work with the library. Will look into that next.

**Comment by benjie** [comment]
Second attempt:

```
benjie@Benjie-Box:~/Dev/graphile/graphile-engine/postgraphile$ cat repro1379.js 
const { makePluginHook, postgraphile } = require('./build');
const PgPubsub = require('@graphile/pg-pubsub').default;

const common = {
  pluginHook: makePluginHook([PgPubsub]),
  appendPlugins: [],
  graphileBuildOptions: {
    connectionFilterRelations: true,
  },
  subscriptions: true,
  simpleSubscriptions: true,
  subscriptionAuthorizationFunction: 'private.validate_subscription',
};

const dev = {
  ...common,
  retryOnInitFail: true,
  watchPg: true,
  dynamicJson: true,
  setofFunctionsContainNulls: false,
  ignoreRBAC: false,
  ignoreIndexes: true,
  showErrorStack: 'json',
  extendedErrors: ['hint', 'detail', 'errcode'],
  exportGqlSchemaPath: 'schema.graphql',
  graphiql: true,
  enhanceGraphiql: true,
  //ownerConnectionString: 'postgres://postgres:postgres@localhost:5450/postgres',
  allowExplain() {
    // TODO: customise condition!
    return true;
  },
  enableQueryBatching: true,
  legacyRelations: 'omit',
  // pgSettings(req) {
  //   /* TODO */
  // },
  //jwtSecret: process.env.JWT_SECRET,
  //jwtPgTypeIdentifier: 'public.jwt_token',
};

const middleware = postgraphile('postgres:///issue1379', 'public', dev);
require('http').createServer(middleware).listen(5000);
benjie@Benjie-Box:~/Dev/graphile/graphile-engine/postgraphile$ node repro1379.js 
0 error(s) in 89.63ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
0 error(s) in 10.06ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
0 error(s) in 5.64ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
0 error(s) in 6.80ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
```

Same operation.

Result:

```
{
  "errors": [
    {
      "errcode": "P0001",
      "extensions": {
        "exception": {
          "errcode": "P0001"
        }
      },
      "message": "topic: postgraphile:anything",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listen"
      ],
      "stack": [
        "error: topic: postgraphile:anything",
        "    at Parser.parseErrorMessage (/home/benjie/Dev/graphile/graphile-engine/postgraphile/node_modules/pg-protocol/dist/parser.js:278:15)",
        "    at Parser.handlePacket (/home/benjie/Dev/graphile/graphile-engine/postgraphile/node_modules/pg-protocol/dist/parser.js:126:29)",
        "    at Parser.parse (/home/benjie/Dev/graphile/graphile-engine/postgraphile/node_modules/pg-protocol/dist/parser.js:39:38)",
        "    at Socket.<anonymous> (/home/benjie/Dev/graphile/graphile-engine/postgraphile/node_modules/pg-protocol/dist/index.js:8:42)",
        "    at Socket.emit (events.js:314:20)",
        "    at addChunk (_stream_readable.js:307:12)",
        "    at readableAddChunk (_stream_readable.js:282:9)",
        "    at Socket.Readable.push (_stream_readable.js:221:10)",
        "    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"
      ]
    }
  ]
}
```

Cannot reproduce this issue.

**Comment by UchihaVeha** [comment]
I checked it. For Simple Subscription, that works fine, but I use a custom subscription, and for that, it doesn't work

SessionPlugin.ts
```
import { makeExtendSchemaPlugin, gql, embed } from 'graphile-utils';

const sessionTopicFromContext = (
  _args: any,
  context: any,
  _resolveInfo: any,
) => {
  const { uid } = context.jwtClaims;
  const sessionId = _args?.input?.sessionId;
  if (uid && sessionId) {
    return `graphql:session:${sessionId}`;
  } else {
    throw new Error("You're not logged in");
  }
};

const SessionPlugin = makeExtendSchemaPlugin(({ pgSql: sql }) => ({
  typeDefs: gql`
        type SessionSubscriptionPayload {
            session: Session
            event: String
        }

        input SessionUpdateInput {
            sessionId: Int!
        }

        extend type Subscription {
            """
            Triggered when the current user's data changes:

            - direct modifications to the user
            - when their organization membership changes
            """
            sessionUpdated(input: SessionUpdateInput!): SessionSubscriptionPayload @pgSubscription(topic: ${embed(
              sessionTopicFromContext,
            )})
        }
    `,

  resolvers: {
    SessionSubscriptionPayload: {
      async session(
        event,
        _args,
        _context,
        { graphile: { selectGraphQLResultFromTable } },
      ) {
        const rows = await selectGraphQLResultFromTable(
          sql.fragment`public.sessions`,
          (tableAlias, sqlBuilder) => {
            sqlBuilder.where(
              sql.fragment`${tableAlias}.id = ${sql.value(event.subject)}`,
            );
          },
        );
        return rows[0];
      },
    },
  },
}));

export default SessionPlugin;

```

```
subscription UpdateSession($sessionId: Int!) {
  sessionUpdated(input: {sessionId: $sessionId}) {
      session {
         ...SessionEntry
      }
      event
  }
}
```

**Comment by benjie** [comment]
Correct; that option is only used with simple subscriptions. For custom subscriptions you use the topic callback to enforce whatever permissions relate to that specific subscription field :+1:

**Comment by benjie** [comment]
(See the [example in the docs](https://www.graphile.org/postgraphile/subscriptions/#custom-subscriptions):

```js
const currentUserTopicFromContext = (_args, context, _resolveInfo) => {
  if (context.jwtClaims.user_id) {
    return `graphql:user:${context.jwtClaims.user_id}`;
  } else {
    throw new Error("You're not logged in");
  }
};
```

)

**Comment by UchihaVeha** [comment]
Can I do a request to the database in this callback to check to have user access to a specific session? For example, the user can have many sessions I can't put that data in JWT, I pass session id into the argument, the user should subscribe and receive updates to a specific session-id but I should check to have user access to subscribe specific session

**Comment by benjie** [comment]
Yep; `topic` can be an `async` function so you can do what you like in it. It's passed context (which contains `pgClient`) as the second argument.
