### ISSUE TITLE
Starting postgraphile on cli with --subscriptions fails in 4.11.0-alpha.0

### ISSUE THREAD

**Issue by benbender** [graphile/postgraphile#1416]
Hey,

just wanted to try the new subscriptions-implementation, but sadly have to report that even the startup of postgraphile fails:

```
$ postgraphile --subscriptions --connection XXX
/XXX/node_modules/postgraphile/build/postgraphile/http/subscriptions.js:47
        throw new Error(`Invalid value for \`websockets\` option: '${options.websockets}'`);
              ^

Error: Invalid value for `websockets` option: 'undefined'
    at Object.enhanceHttpServerWithWebSockets (/XXX/node_modules/postgraphile/build/postgraphile/http/subscriptions.js:47:15)
    at Object.<anonymous> (/XXX/node_modules/postgraphile/build/postgraphile/cli.js:451:29)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/XXX/node_modules/postgraphile/cli.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
error Command failed with exit code 1.
````

Even with the options explicitly set, it fails:

````
$ postgraphile --subscriptions --websockets v1 --websocket-operations all --connection XXX
/XXX/node_modules/postgraphile/build/postgraphile/http/subscriptions.js:47
        throw new Error(`Invalid value for \`websockets\` option: '${options.websockets}'`);
              ^

Error: Invalid value for `websockets` option: 'undefined'
    at Object.enhanceHttpServerWithWebSockets (/XXX/node_modules/postgraphile/build/postgraphile/http/subscriptions.js:47:15)
    at Object.<anonymous> (/XXX/node_modules/postgraphile/build/postgraphile/cli.js:451:29)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/XXX/node_modules/postgraphile/cli.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
````

**Comment by benjie** [comment]
4.11.0-alpha.1 is out with the fix.
