### ISSUE TITLE
JWT non-scalar claims

### ISSUE THREAD

**Issue by ccakes** [graphile/postgraphile#1423]
### Summary

I'd like to be able to create JWT claims that aren't just scalars. This actually seems to (somewhat) work but Postgraphile throws an error so I suspect there's an issue somewhere in what I'm doing.

In short, I have users who can be members of one or more organisations and I want to represent that in the JWT.

eg (test JWT)
```json
{
  "exp": 1609176457,
  "id": "spxagpYEqu",
  "email": "user@example.com",
  "organisations": [
    {
      "id": "ELYssnYmpi",
      "role": "Owner"
    }
  ],
  "iat": 1609172857,
  "aud": "postgraphile",
  "iss": "postgraphile"
}
```

### Additional context

With this JWT type and auth function (mostly copied from the docs)
```sql
CREATE TYPE public.membership AS (
  id text,
  role text
);

CREATE TYPE public.jwt_token AS (
  exp integer,
  id text,
  email text,
  role text,
  organisations public.membership[],
  projects public.membership[]
);

CREATE OR REPLACE FUNCTION public.authenticate (email text, password text)
  RETURNS public.jwt_token
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $$
DECLARE
  _account data.account;
  _organisations public.membership[];
BEGIN
  SELECT
    * INTO _account
  FROM
    data.account
  WHERE
    account.email = authenticate.email;

  IF _account.password = crypt(authenticate.password, _account.password) THEN
    -- Fetch org memberships
    SELECT
      array_agg((organisation_id, role)::public.membership) INTO _organisations
    FROM public.organisation_members
    WHERE
      user_id = _account.external_id;

    RETURN (
      extract(epoch FROM now() + interval '1 hour'),
      _account.external_id,
      _account.email,
      _organisations
    )::public.jwt_token;
  ELSE
    RETURN NULL;
  END IF;
END;
$$;
```

☝️ This _seems_ to work fine. The JWT is generated and Postgraphile happily accepts it and all the right fields are set as expected. When calling the authenticate mutation though I get this logged..
```
Error: Internal graphile-build-pg error: should not attempt to tweak an array, please process array before tweaking (type: "public._membership")
    at Object.pgTweakFragmentForTypeAndModifier (/path/to/node_modules/graphile-build-pg/src/plugins/PgTypesPlugin.js:367:25)
    at map (/path/to/node_modules/graphile-build-pg/src/plugins/PgJWTPlugin.js:140:29)
    at Array.map (<anonymous>)
    at tweaker (/path/to/node_modules/graphile-build-pg/src/plugins/PgJWTPlugin.js:136:39)
    at Object.pgTweakFragmentForTypeAndModifier (/path/to/node_modules/graphile-build-pg/src/plugins/PgTypesPlugin.js:305:18)
    at withBuilder (/path/to/node_modules/graphile-build-pg/src/plugins/makeProcField.js:399:19)
    at Object.queryFromResolveData (/path/to/node_modules/graphile-build-pg/src/queryFromResolveDataFactory.js:71:5)
    at makeQuery (/path/to/node_modules/graphile-build-pg/src/plugins/makeProcField.js:371:23)
    at resolve (/path/to/node_modules/graphile-build-pg/src/plugins/makeProcField.js:672:31)
    at resolveField (/path/to/node_modules/graphql/execution/execute.js:466:18)
```
Any pointers at what I'm doing wrong?

Also side question: I'd much rather the JWT `organisations` claim be an object rather than an array - any tips for that would also be hugely appreciated!

eg
```json
{
  "exp": 1609176457,
  "id": "spxagpYEqu",
  "email": "user@example.com",
  "organisations": {
    "ELYssnYmpi": "Owner"
  },
  "iat": 1609172857,
  "aud": "postgraphile",
  "iss": "postgraphile"
}

**Comment by benjie** [comment]
The JWT that PostGraphile consumes and produces is intended to be a string-scalar map (i.e. `{[key: string]: string | number }`); usage outside of this is unsupported. That said, if you'd like to send a PR that fixes this issue, that would be welcome.

Not sure, but maybe using JSON as the type of `organizations` and `projects` might bypass this.

**Comment by ccakes** [comment]
Initially I ended up removing some of the extra info from my claims set and I just fetch this for each request. Slower but during dev it's fine and I can deal with it later.

In thinking a bit about your reply I realised I could probably get (at least the data structure..) I wanted using `hstore`. A quick test now - this seems to work and doesn't throw any errors to the log

```sql

CREATE DATABASE test;
\c test

CREATE EXTENSION hstore;

CREATE TYPE public.jwt_token AS (
  exp integer,
  id text,
  email text,
  role text,
  organisations hstore,
  projects hstore
);

CREATE OR REPLACE FUNCTION public.authenticate (email text, password text)
  RETURNS public.jwt_token
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $$
BEGIN
  RETURN (
    extract(epoch FROM now() + interval '1 hour'),
    'some_id_value',
    'me@example.com',
    'a role',
    '"org_a" => "Owner", "org_2" => "Member"'::hstore,
    null
  )::public.jwt_token;
END;
$$;
```

With this the `authenticate` mutation returns a well formed JWT. I haven't checked how Postgraphile handles this when it receives the token.. not even sure how I'd test that 🤔
