### ISSUE TITLE
Error: pgJwtTypeIdentifier was specified without pgJwtSecret

### ISSUE THREAD

**Issue by MoltenCoffee** [graphile/postgraphile#1429]
### Summary

I'm trying to run postgraphile (library mode) locally but receive this error:

```
Error: pgJwtTypeIdentifier was specified without pgJwtSecret
at PgJWTPlugin/init/PgJWT (J:\...\node_modules\graphile-build-pg\node8plus\plugins\PgJWTPlugin.js:37:13)
    at SchemaBuilder.applyHooks (J:\...\node_modules\graphile-build\node8plus\SchemaBuilder.js:252:20)
    at SchemaBuilder.createBuild (J:\...\node_modules\graphile-build\node8plus\SchemaBuilder.js:313:10)
    at SchemaBuilder.buildSchema (J:\...\node_modules\graphile-build\node8plus\SchemaBuilder.js:321:26)
    at SchemaBuilder.watchSchema (J:\...\node_modules\graphile-build\node8plus\SchemaBuilder.js:389:34)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Object.exports.watchPostGraphileSchema (J:\...\node_modules\postgraphile-core\node8plus\index.js:253:5)
    at async createGqlSchema (J:\...\node_modules\postgraphile\build\postgraphile\postgraphile.js:79:21)
```

In my options I have the following options related to JWTs:

```js
const options = {
    jwtSecret: privKey,
    jwtPublicKey: pubKey,
    jwtPgTypeIdentifier: "users_public.jwt_token",
    defaultRole: "api_noauth",
    jwtSignOptions: { issuer: "XX", algorithm: "RS256" },
    jwtVerifyOptions: { issuer: "XX", algorithms: ["RS256"] },
}
```

Where privKey and pubKey are created by the Node crypto library as follows:

```js
generateKeyPair(
    "rsa",
    {
        modulusLength: 4096,
        publicKeyEncoding: {
            format: "pem",
            type: "pkcs1",
        },
        publicKeyEncoding: {
            format: "pem",
            type: "pkcs1",
        },
    },
   (....)
);
```

and then saved to disk and read via `fs.readFileSync(privKeyPath, { encoding: "utf8" })`.

Am I using private and public keys wrong in this context? Did I overlook a typo somewhere?
Thanks in advance!

### Additional context

Windows 10
PostgreSQL 13.1
Node v15.5.0
Postgraphile 4.10.0

**Comment by MoltenCoffee** [comment]
My bad!

It had nothing to do with postgraphile, but a problem with async functions, as the reading of the keys from file was done inside an asynchronous function. A simple await fixed the problem!
