### ISSUE TITLE
graphql-ws@4.1.4 breaks postgraphile

### ISSUE THREAD

**Issue by bjorkegeek** [graphile/postgraphile#1439]
### Summary
The pulled in dependency graphql-ws breaks postgraphile for version graphql-ws@4.1.4. Explicit downgrade to graphql-ws@4.1.3 is a proper workaround

### Steps to reproduce

In an empty directory, do
```
yarn add postgraphile
```
Then, run node and try to require postgraphile:
```
Welcome to Node.js v12.20.1.
Type ".help" for more information.
> require('postgraphile')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/david/mehmeh/node_modules/graphql-ws/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/david/mehmeh/node_modules/postgraphile/build/postgraphile/http/subscriptions.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Expected results

No exception thrown when require'ing postgraphile

### Actual results

See above

### Additional context

Tested on Fedora 33. yarn@1.22.10 nodejs@14.15.4

### Possible Solution

```
yarn add postgraphile graphql-ws@4.1.3
```
works. Perhaps dependencies for postgaphile should be updated until this is resolved.

**Comment by benjie** [comment]
:crossed_fingers: resolved by https://github.com/enisdenjo/graphql-ws/commit/8f70b02ec1ed1b88fd80e7e04eecf4552b382bbc

**Comment by bjorkegeek** [comment]
Confirmed -- it works now.
