### ISSUE TITLE
Greenplum Support

### ISSUE THREAD

**Issue by yehia2amer** [graphile/postgraphile#1447]
### Summary

Is There any plans to support [Greenplum](https://tanzu.vmware.com/greenplum) which is An open-source Massively Parallel Datawarehouse based on Postgres for Analytics, machine learning and AI ?

### Additional context

I Tried to run postgraphile on our Greenplum Datalake (Greenplum Database 5). but I got the error below, I Think this is because 
Greenplum depends on old Postgresql versions (ex: our datalake uses the latest version of Greenplum 5 which depends on PostgreSQL 8.3.23)
 
```
PostGraphile v4.11.0 server listening on port 5000 🚀

  ‣ GraphQL API:         http://0.0.0.0:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://0.0.0.0:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: (watching)
  ‣ Postgres schema(s):  
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v12.20.1 on linux x64
  ‣ Join Mark Lipscombe in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

error: COALESCE could not convert type text[] to "char"[]
    at Parser.parseErrorMessage (/postgraphile/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/postgraphile/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/postgraphile/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/postgraphile/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by benjie** [comment]
PostGraphile relies on the JSON capabilities introduced in PostgreSQL 9.4; anything older than that would be an incredibly large lift to support, so it's currently out of scope. Similar issues with Redshift.
