### ISSUE TITLE
Postgraphile collection queries erroring when using 'mergeSchemas'

### ISSUE THREAD

**Issue by danielMadeRenovation** [graphile/postgraphile#1496]
I have the following code: 

versions: 
```
    "postgraphile": "^4.12.3",
    "postgraphile-apollo-server": "^0.1.1",
    "postgraphile-plugin-connection-filter": "^2.2.1",

    // `mergeSchemas`: i'm aware if it's an issue here, this is not your problem, but thought I'd include it to be exhaustive
    "graphql-tools": "^7.0.5",
```

```javascript
export const getGraphqlSchema = async () => {
  const { schema: pgSchema, plugin: PgPlugin } = await getPgSchema();
  const customSchema = getCustomSchema();

  const schema = mergeSchemas({
    schemas: [pgSchema, customSchema],
  });
  const schemaWithMiddleware = applyMiddleware(schema, ...middlewares);

  return {
    schema: schemaWithMiddleware,
    plugins: [PgPlugin],
    formatResponse,
    context,
    middleware: [],
  };
};
```

Where `customSchema` is using `makeExecutableSchema` from `apollo-server-express` and pg schema instantiation looks like this: 

```javascript
export const getPgSchema = async () => {
  const { pool } = await setupConnection();

  return makeSchemaAndPlugin(
    pool,
    'public', // PostgreSQL schema to use
    {
      // PostGraphile options, see:
      // https://www.graphile.org/postgraphile/usage-library/

      // require("@graphile-contrib/pg-many-to-many"),
      appendPlugins: [require('@graphile-contrib/pg-simplify-inflector')],
    },
  );
};
```

This strategy works for everything except collection queries. All other queries/mutations from both postgraphile and custom schemas work perfectly. If I try to run something like:

```
query GetUsers {
  users {
    nodes {
      id
    }
  }
}
```

I get this error:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'map' of undefined",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "users",
        "nodes"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'map' of undefined",
            "    at resolve (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphile-build-pg/src/plugins/PgTablesPlugin.js:501:44)",
            "    at field.resolve (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
            "    at resolveField (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphql/execution/execute.js:464:18)",
            "    at executeFields (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphql/execution/execute.js:590:12)",
            "    at /Users/daniellemburg/Desktop/made/made-web-api/node_modules/graphql/execution/execute.js:469:16",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": {
    "users": null
  }
}
```

I stepped through the resolver, and when it gets ready to execute the sql against the pg client, the query itself is just this: ` select `. Naturally, this does not return any results, haha.

Note that I am using `@graphile-contrib/pg-simplify-inflector` but the same error happens regardless of using this plugin.

All collection queries work fine when I do not use `mergeSchemas`. Any thoughts?

Thanks!

**Comment by benjie** [comment]
Something you’re doing by manipulating the schema is breaking the lookahead logic. I don’t know what/why, but you could maybe solve it by creating a sacrificial schema that defers to PostGraphile to be mangled by the tooling you’re using in PostGraphile’s place?

[semi-automated message] Thanks for your question; hopefully we're on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).

**Comment by blevine** [comment]
I am also seeing this problem.  It occurs even if the Postgraphile generated schema is the only schema passed to mergeSchemas. I'm not sure how mergeSchemas is mangling the schema or what the suggested work-around is.

**Comment by danielMadeRenovation** [comment]
The solution is to buy into the "postgraphile way". The merge schemas plugin within the postraphile plugin system works great. 

I've since moved off of Postgraphile (need a federated schema), but the above adoption was very helpful in our initial iterations.

**Comment by blevine** [comment]
Unfortunately, the plugin you're referring to doesn't really do a merge.  It _extends_ the Postgraphile schema with additional typedefs and resolvers. The typedefs can't include the root fields like Query or Postgraphile will throw an error because of duplicate Query fields instead of merging the Query fields.  In my case, I'm generating the non-Postgraphile schema using TypeGraphql. Pulling the typedefs out of the generated schema excluding the root fields is turning out to be difficult

**Comment by blevine** [comment]
As a final thought (for anyone else finding this issue): For my application, the majority of my GraphQL API accesses other services via their remote APIs rather than accessing a database.  So Postgraphile might not be the most appropriate technology for my particular case where the primary use case is remote service access and direct DB access is secondary. Regardless, I still wanted to try out Postgraphile.  Since the Postgraphile-generated schema would be the "secondary" schema, I wanted to integrate the Postgraphile-generated schema into my "primary" schema and not the other way around.

I finally got this to work by using graphql-tools _stitching_ rather than _merging_.  I'm guessing this effectively provides the "sacrificial schema" that was suggested by @benjie.

**Comment by danielMadeRenovation** [comment]
I didn't understand what was "sacrificial" about that strategy. Can you
elaborate?

**Comment by blevine** [comment]
I wasn't quite sure what @benjie meant by "sacrificial" either, but I assumed that he meant a proxy schema whose function is to delegate to another schema. The stitched schema is that proxy.  If sacrificial schema has some other meaning, @benjie can correct me.

**Comment by benjie** [comment]
@blevine that’s exactly what I meant.
