### ISSUE TITLE
Error with byte sequence 0xe2 0x80 0x99 in a latin1 postgres db

### ISSUE THREAD

**Issue by wagneracacio** [graphile/postgraphile#1513]
### Summary

i've been receive an error when i try to connect postgraphile in a postgres 9.5 encoded with LATIN!

### Actual results

this is the log of problem when i try to execute postgraphile by docker

error: character with byte sequence 0xe2 0x80 0x99 in encoding "UTF8" has no equivalent in encoding "LATIN1"
    at Parser.parseErrorMessage (/postgraphile/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/postgraphile/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/postgraphile/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/postgraphile/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

### Possible Solution

i check character correspondence of byte 0xe2 0x80 0x99 and caracter is ’, postgresgraphile is not able to check latin encoded dbs or maybe this can be a problem with comments of sql who have this caracters?

**Comment by benjie** [comment]
I recommend using UTF8 in your database (and everywhere else, for that matter). It seems like you're trying to store the character `’` into a LATIN1 database but that's not possible... what would you like PostGraphile to do in this case.

**Comment by wagneracacio** [comment]
unfortunately it's a third-party database that I can't change the encode, in case i'm not trying to store data only show data with "docker run --init -p 5000:5000 graphile/postgraphile --connection postgres://bduser:dbpass@myip:port/db --schema dbschema --watch
" and this bring me the error

**Comment by benjie** [comment]
Try adding a `.postgraphilerc.js` file with the following contents:

```js
module.exports = {
  options: {
    host: '0.0.0.0',
    pgSettings: {
      'client_encoding': 'UTF8'
    }
  }
};
```

Here's the relevant line from our Dockerfile: https://github.com/graphile/postgraphile/blob/7b02cf221ca39ae9c94f8a031e5d82a0f6841d94/Dockerfile#L36

**Comment by wagneracacio** [comment]
i tried with the client_encoding but the problem continue with the same log

**Comment by benjie** [comment]
I'm afraid I don't know where that character is coming from, I don't see it in any non-comments in our source code. Are you sure it's not coming from the query you're issuing?

Try following the debugging steps to see if you can make sense of it: https://www.graphile.org/postgraphile/debugging/ in particular set the `DEBUG` envvar to `*,-graphile-builder` and see if it outputs anything helpful.
