### ISSUE TITLE
Error: Cannot find module '@graphile/pg-pubsub'

### ISSUE THREAD

**Issue by warcayac** [graphile/postgraphile#1623]
I'm running Postgraphile as a Docker container, where part of `docker-compose.yaml` is:
```
  graphql:
    build: 
      context: ./graphql
    container_name: xyz-gql
    restart: unless-stopped
    env_file: 
      - ./graphql/.env
    depends_on: 
      - db
    networks: 
      cyp-net:
        ipv4_address: 172.27.0.3
      lan:
        ipv4_address: 192.168.0.201
    ports: 
      - 5000:5000
    command: [
      "--plugins", "@graphile/pg-pubsub",
      "--subscriptions",
      "--simple-subscriptions",
      "--connection", "....................", 
      "--owner-connection", "......................................", 
      "--watch", 
      "--schema", "${DEFAULT_SCHEMA}", 
      "--default-role", "${DEFAULT_ROLE}",
      "--jwt-secret", "${JWT_SECRET}", 
      "--jwt-token-identifier", "${JWT_TOKEN_ID}",
      "--dynamic-json",
      "--no-setof-functions-contain-nulls",
      "--no-ignore-rbac",
      "--no-ignore-indexes",
      "--show-error-stack", "json",
      "--extended-errors", "hint,detail,errcode",
      "--enable-query-batching",
      "--legacy-relations", "omit",
      "--export-schema-graphql", "xyz_schema.graphql",
      "--append-plugins", "@graphile-contrib/pg-simplify-inflector",
      "--simple-collections", "only",
      "--enhance-graphiql"
    ]
```

And my `./graphql/Dockerfile` is:

```
FROM graphile/postgraphile:latest
RUN yarn add @graphile/pg-pubsub
RUN yarn add @graphile-contrib/pg-simplify-inflector
```

Recently I'm getting error messages for this service:

```
xyz-gql  | 2022-04-30T01:58:38.784821368Z Error: Cannot find module '@graphile/pg-pubsub'
xyz-gql  | 2022-04-30T01:58:38.784825316Z Require stack:
xyz-gql  | 2022-04-30T01:58:38.784829864Z - /postgraphile/build/postgraphile/cli.js
xyz-gql  | 2022-04-30T01:58:38.784833481Z - /postgraphile/cli.js
xyz-gql  | 2022-04-30T01:58:38.784837169Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
xyz-gql  | 2022-04-30T01:58:38.784841717Z     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
xyz-gql  | 2022-04-30T01:58:38.784845635Z     at Module.require (internal/modules/cjs/loader.js:887:19)
xyz-gql  | 2022-04-30T01:58:38.784849312Z     at require (internal/modules/cjs/helpers.js:74:18)
xyz-gql  | 2022-04-30T01:58:38.784852859Z     at /postgraphile/build/postgraphile/cli.js:57:27
xyz-gql  | 2022-04-30T01:58:38.784857779Z     at Array.map (<anonymous>)
xyz-gql  | 2022-04-30T01:58:38.784862297Z     at extractPlugins (/postgraphile/build/postgraphile/cli.js:55:35)
xyz-gql  | 2022-04-30T01:58:38.784866796Z     at Object.<anonymous> (/postgraphile/build/postgraphile/cli.js:67:62)
xyz-gql  | 2022-04-30T01:58:38.784870864Z     at Module._compile (internal/modules/cjs/loader.js:999:30)
xyz-gql  | 2022-04-30T01:58:38.784874722Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
xyz-gql  | 2022-04-30T01:58:38.784878579Z   code: 'MODULE_NOT_FOUND',
xyz-gql  | 2022-04-30T01:58:38.784882206Z   requireStack: [ '/postgraphile/build/postgraphile/cli.js', '/postgraphile/cli.js' ]
xyz-gql  | 2022-04-30T01:58:38.784885853Z }
xyz-gql  | 2022-04-30T01:58:43.516172912Z internal/modules/cjs/loader.js:818
xyz-gql  | 2022-04-30T01:58:43.516208682Z   throw err;
xyz-gql  | 2022-04-30T01:58:43.516216557Z   ^
```

Any idea about what's going on?

**Comment by benjie** [comment]
You have postgraphile installed globally but pubsub installed locally, so PostGraphile can’t see pubsub. You’d have an easier time using a node base rather than the postgraphile image.

**Comment by warcayac** [comment]
Thanks, I've followed [your tutorial](https://www.graphile.org/postgraphile/running-postgraphile-in-docker/#create-postgraphile-dockerfile), and my current `Dockerfile` is:

```
FROM node:alpine

# Install PostGraphile and PostGraphile connection filter plugin
RUN npm install -g postgraphile
RUN npm install -g @graphile/pg-pubsub
RUN npm install -g @graphile-contrib/pg-simplify-inflector

EXPOSE 5000
ENTRYPOINT ["postgraphile", "-n", "0.0.0.0"]
```
After creating my service I'm getting this message:
```
error: unknown option `--simple-subscriptions'
```
why?

**Comment by benjie** [comment]
You should remove the `-g` for all three commands I think (but that's not your issue, just it's generally best not to use `-g`)

> --plugins must be the first argument to postgraphile if specified

^ This is your issue.

> `ENTRYPOINT ["postgraphile", "-n", "0.0.0.0"]`

Note how `-n` is your first argument, whereas you need it to be `--plugins`

```Dockerfile
ENTRYPOINT ["postgraphile", "--plugins", "@graphile/pg-pubsub", "-n", "0.0.0.0", "--simple-subscriptions"]
```

[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).
