### ISSUE TITLE
Postgraphile for bulk data processing

### ISSUE THREAD

**Issue by jayadevanm** [graphile/postgraphile#1627]
Is Postgraphile recommended for bulk data fetches? I am trying to get all data for a specific client. If the LIMIT is set to 30000 (i.e. only those many records fetched, it works). Increasing it to 300000 throws this error.
```
Traceback (most recent call last):
  File "/home/jayadevan/.local/lib/python3.10/site-packages/gql/transport/aiohttp.py", line 306, in execute
    result = await resp.json(content_type=None)
  File "/home/jayadevan/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1098, in json
    await self.read()
  File "/home/jayadevan/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/home/jayadevan/.local/lib/python3.10/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/home/jayadevan/.local/lib/python3.10/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/home/jayadevan/.local/lib/python3.10/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jayadevan/scrpt/./pgraphile.py", line 36, in <module>
    result = client.execute(query)
  File "/home/jayadevan/.local/lib/python3.10/site-packages/gql/client.py", line 355, in execute
    data = loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/jayadevan/.local/lib/python3.10/site-packages/gql/client.py", line 252, in execute_async
    return await session.execute(
  File "/home/jayadevan/.local/lib/python3.10/site-packages/gql/client.py", line 1143, in execute
    result = await self._execute(
  File "/home/jayadevan/.local/lib/python3.10/site-packages/gql/client.py", line 1049, in _execute
    result = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

real	0m14.572s
user	0m0.695s
sys	0m0.168s
```

**Comment by benjie** [comment]
PostGraphile builds the response in memory and then stringifies it and sends it to the client (it does not stream it out bit by bit, as that could easily fall foul of GraphQL's error handling requirements where errors must "bubble up"). As such, it is limited by the memory limits that Node applies to it. PostGraphile is generally intended to serve web and mobile clients, expecting to supply kilobytes and up to a few megabytes. Above that, it's up to you to determine the limits.

Normally this kind of requirement is solved via pagination: fetch 1,000 rows at a time and do follow up (or even concurrent!) requests for the next 1000; repeat until complete.

The GraphQL Working Group is currently in the process of standardizing a `@stream` directive that will allow a single request to supply this large amount of data whilst building the individual payloads bit by bit, but it's not quite ready yet (we're still iterating on the payload and resolver return formats).

[semi-automated message] Thanks for your question; hopefully we're well on the way to helping you solve your issue. This doesn't currently seem to be a bug in the library so I'm going to close the issue, but please feel free to keep requesting help below and if it does turn out to be a bug we can definitely re-open it 👍

You can also ask for help in the #help-and-support channel in [our Discord chat](http://discord.gg/graphile).
