### ISSUE TITLE
Graphile Migrate issues on DBs with SSL

### ISSUE THREAD

**Issue by xKakima** [graphile/postgraphile#1629]
### Summary
```
"...DBSTUFF?sslmode=require&ssl=true&sslrootcert=ca.crt"
```

This code works if you're using `graphile-migrate watch` but it fails when you're going to use `graphile-migrate reset --erase`

### Additional context

error logs
```
$ graphile-migrate reset --erase
node:internal/crypto/keys:570
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received null
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at new Hmac (node:internal/crypto/hash:132:9)
    at Object.createHmac (node:crypto:162:10)
    at createHMAC (C:\Users\Kakima\AppData\Roaming\npm\node_modules\graphile-migrate\node_modules\pg\lib\sasl.js:133:17)
    at Hi (C:\Users\Kakima\AppData\Roaming\npm\node_modules\graphile-migrate\node_modules\pg\lib\sasl.js:137:13)
    at Object.continueSession (C:\Users\Kakima\AppData\Roaming\npm\node_modules\graphile-migrate\node_modules\pg\lib\sasl.js:32:24)
    at Client._handleAuthSASLContinue (C:\Users\Kakima\AppData\Roaming\npm\node_modules\graphile-migrate\node_modules\pg\lib\client.js:257:10)
    at Connection.emit (node:events:520:28)
    at C:\Users\Kakima\AppData\Roaming\npm\node_modules\graphile-migrate\node_modules\pg\lib\connection.js:115:12 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by benjie** [comment]
Do you have those same details in the `rootConnectionString`?

**Comment by xKakima** [comment]
CA file required
