### ISSUE TITLE
How Can I Find the Cause of a "permission denied for table ___" Error?

### ISSUE THREAD

**Issue by machineghost** [graphile/postgraphile#1648]
### Summary

I recently tried to switch an existing database to use the two schema (public/private) approach, and as a result I now run postgraphile as the user `public_postgraphile`.  That user *does* have permission granted to edit my "themes" table:

```
 SELECT grantee, privilege_type FROM information_schema.role_table_grants WHERE table_name='themes';

       grantee       | privilege_type 
---------------------+----------------
 public_postgraphile | INSERT
 public_postgraphile | SELECT
 public_postgraphile | UPDATE
 public_postgraphile | DELETE
```

However, whenever I try to use the GraphQL interface to update a `themes` record, I get:

```
error: permission denied for table themes
    at Parser.parseErrorMessage (/home/me/project/admin/server/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/me/project/admin/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/me/project/admin/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/me/project/admin/server/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  locations: [ { line: 3, column: 9 } ],
  path: [ 'updateTheme' ]
}
```

Since the user should have the appropriate grant/permission, I'm not sure what to fix.  Any further explanation of what the error is complaining about would be appreciated.

### Additional context

"postgraphile": "^4.10.0",

P.S. I also granted the user schema permissions with:

     grant usage on schema public to public_postgraphile;

**Comment by machineghost** [comment]
It turns out I was just being dumb and not understanding how:

    pgDefaultRole: 'public_anonymous',

worked.  I was thinking "`public_postgraphile` can access this table, and Postgraphile is running as that user, so I shouldn't be getting a permission error" ... but (of course) without a JWT specified the `public_postgraphile` permissions don't even matter.

Sorry to bother you.
