### ISSUE TITLE
Cannot run any queries because of an identity claim with a colon

### ISSUE THREAD

**Issue by Fyb3roptik** [graphile/postgraphile#1735]
### Summary

I am getting this error when running Postgraphile as well as appsync console directly. I am using Cognito user pools for Auth

```json
{
    "errorType": "error",
    "errorMessage": "invalid configuration parameter name \"appsync.identity_claims_cognito:username\"",
    "code": "42602",
    "length": 215,
    "name": "error",
    "severity": "ERROR",
    "detail": "Custom parameter names must be two or more simple identifiers separated by dots.",
    "file": "guc.c",
    "line": "8095",
    "routine": "find_option",
    "stack": [
        "error: invalid configuration parameter name \"appsync.identity_claims_cognito:username\"",
        "    at Parser.parseErrorMessage (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:287:98)",
        "    at Parser.handlePacket (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:126:29)",
        "    at Parser.parse (/opt/nodejs/node_modules/pg-protocol/dist/parser.js:39:38)",
        "    at TLSSocket.<anonymous> (/opt/nodejs/node_modules/pg-protocol/dist/index.js:11:42)",
        "    at TLSSocket.emit (events.js:400:28)",
        "    at TLSSocket.emit (domain.js:475:12)",
        "    at addChunk (internal/streams/readable.js:293:12)",
        "    at readableAddChunk (internal/streams/readable.js:267:9)",
        "    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)",
        "    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)"
    ]
}
```

### Steps to reproduce

Create a new project and use a user pool to authenticate

### Expected results

Need this `appsync.identity_claims_cognito:username` to be this `appsync.identity_claims_cognito.username`

### Actual results

Forces a null list back when running a query because of the failure

**Comment by benjie** [comment]
Where’s that even coming from? Is it a bug in your pgSettings configuration?

**Comment by Fyb3roptik** [comment]
I honestly have no idea. I am using Aurora and Postgres 15 and just did the default install

**Comment by Fyb3roptik** [comment]
Here is what the INFO appsync request looks like. Notice under identity there is cognito:username and it should be cognito.username. I cannot find this in the code anywhere for postgraphile. This happens when I run it from appsync console

```json
{
    "arguments": {
        "first": 10
    },
    "identity": {
        "claims": {
            "sub": "185183c0-7061-7069-c98b-633c0d29e287",
            "email_verified": true,
            "iss": "https://cognito-idp.us-west-2.amazonaws.com/someurl",
            "cognito:username": "185183c0-7061-7069-c98b-633c0d29e287",
            "given_name": "Name",
            "picture": "url",
            "origin_jti": "52232f0a-69bd-4111-bf9d-814de96a6102",
            "aud": "1nvkj2901lrft5fp5aga0f3o6o",
            "event_id": "71ec9b99-8b38-40f9-acff-330e1e6be9a6",
            "token_use": "id",
            "auth_time": 1690295821,
            "exp": 1690299421,
            "iat": 1690295821,
            "family_name": "Tester",
            "jti": "9f297be3-4308-463f-b08b-ab76115451a8",
            "email": "nick+test@rev-amp.ai"
        },
        "defaultAuthStrategy": "ALLOW",
        "groups": null,
        "issuer": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_tgrAwGyCi",
        "sourceIp": [
            "99.7.64.140"
        ],
        "sub": "185183c0-7061-7069-c98b-633c0d29e287",
        "username": "185183c0-7061-7069-c98b-633c0d29e287"
    },
```

**Comment by Fyb3roptik** [comment]
This appears to be a breaking change made in PG14. https://www.postgresql.org/message-id/5b85039e-99da-5a8f-a42c-59e5660f60f2%40postgresfriends.org

**Comment by Fyb3roptik** [comment]
Submitted an issue on their forums

https://repost.aws/questions/QUssX-kciKQbeAuHNanjdWSQ/appsync-broken-on-postgres-14

I will close this here as its not an issue with Postgraphile
