### ISSUE TITLE
Function that takes array of Timestamp cannot be called?

### ISSUE THREAD

**Issue by angelosarto** [graphile/postgraphile#314]
Perhaps I am calling this wrong but it seems like a function with an array of timestamps cannot be called as it is unclear if this should map to a text array or an array of timestamps.

Minimal example:
```SQL
CREATE OR REPLACE FUNCTION ts_non_array(
  _timestamp TIMESTAMP
) RETURNS TEXT
AS $$
BEGIN
  RETURN 'Hello World';
END
$$ LANGUAGE PLPGSQL VOLATILE;

select ts_non_array('"2013-10-21T13:28:06.419Z"');

CREATE OR REPLACE FUNCTION ts_array(
  _timestamp TIMESTAMP[]
) RETURNS TEXT
AS $$
BEGIN
  RETURN 'Hello World';
END
$$ LANGUAGE PLPGSQL VOLATILE;

select ts_array('{"2013-10-21T13:28:06.419Z","2013-10-21T13:28:06.419Z"}');
```
Outputs "Hello World in both cases

Calling them from graphql
```graphql

mutation {tsNonArray (input: {
  _timestamp: "2013-10-21T13:28:06.419Z"
}) {string}
}
RETURNS
{
  "data": {
    "tsNonArray": {
      "string": "Hello World"
    }
  }
} 
```

Calling the one with the array however
```graphql
mutation {tsArray (input: {
  _timestamp: ["2013-10-21T13:28:06.419Z"]
}) {string}
}

RETURNS
...
errors": [
    {
      "message": "function public.ts_array(text[]) does not exist",
...
```

**Comment by benjie** [comment]
Interesting; could you turn on debugging with `export DEBUG="postgraphql:*"` and tell us what SQL statements are executed?

**Comment by angelosarto** [comment]
It gives some output, but not too much see below:

```
graphql-server_1         | Thu, 19 Jan 2017 23:17:55 GMT postgraphql:request GraphQL query request has begun.
graphql-server_1         | Thu, 19 Jan 2017 23:17:55 GMT postgraphql:request GraphQL query is parsed.
graphql-server_1         | Thu, 19 Jan 2017 23:17:55 GMT postgraphql:request GraphQL query request finished.
graphql-server_1         | 1 error(s) in 6.92ms :: mutation { tsArray(input: {_timestamp: ["2013-10-21T13:28:06.419Z"]}) { string } }
```

**Comment by calebmer** [comment]
@angelosarto it looks like the Postgres query information is missing from the logs. Perhaps try just `DEBUG="postgraphql:postgres"`?

I think the fix we need to implement is add Postgres type information to the queries we send to the database. So:

```sql
select to_json("public"."ts_array"(array[$1, $2, $3]));
```

Would become:

```sql
select to_json("public"."ts_array"(array[$1::timestamp, $2::timestamp, $3::timestamp]));
```

…or we may be able to get away with:

```sql
select to_json("public"."ts_array"(array[$1::timestamp, $2, $3]));
```

To hint the type to Postgres.

**Comment by angelosarto** [comment]
Tried with `DEBUG="postgraphql:postgres"` 

got this output:
```
graphql-server_1         | Fri, 20 Jan 2017 23:29:50 GMT postgraphql:postgres begin
graphql-server_1         | Fri, 20 Jan 2017 23:29:50 GMT postgraphql:postgres select to_json(__local_0__) as value from "public"."ts_array2"(array[$1]) as __local_0__
graphql-server_1         | Fri, 20 Jan 2017 23:29:50 GMT postgraphql:postgres error: function public.ts_array2(text[]) does not exist
graphql-server_1         |     at Connection.parseE (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:554:11)
graphql-server_1         |     at Connection.parseMessage (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:381:17)
graphql-server_1         |     at Socket.<anonymous> (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:117:22)
graphql-server_1         |     at emitOne (events.js:96:13)
graphql-server_1         |     at Socket.emit (events.js:188:7)
graphql-server_1         |     at readableAddChunk (_stream_readable.js:176:18)
graphql-server_1         |     at Socket.Readable.push (_stream_readable.js:134:10)
graphql-server_1         |     at TCP.onread (net.js:551:20)
graphql-server_1         | Fri, 20 Jan 2017 23:29:50 GMT postgraphql:postgres commit
graphql-server_1         | 1 error(s) in 10.41ms :: mutation { tsArray2(input: {_timestamp: ["2013-10-21T13:28:06.419Z"]}) { datetimes } }
```

I also tried with a couple of other types - with INTEGER[] and TEXT[] it works, but I also found it doesn't work with NUMERIC[] as it tries to coerce them all to ints. So we may need to cast each item see below:

SQL (ignore that the field is named _timestamp, got lazy on that copypasta :)
```
CREATE OR REPLACE FUNCTION numeric_array(
  _timestamp NUMERIC[]
) RETURNS TEXT
AS $$
BEGIN
  RETURN 'Hello World';
END
$$ LANGUAGE PLPGSQL VOLATILE;
```

graphql mutation query (wouldn't actually have to be a mutation, but hey)
```
mutation{ numericArray (input: {
  _timestamp: [123.1, 456]
}){string}}
```

graphiql output
```
{
  "data": {
    "numericArray": null
  },
  "errors": [
    {
      "message": "invalid input syntax for integer: \"123.1\"",
      "locations": [
        {
          "line": 64,
          "column": 11
        }
      ],
      "path": [
        "numericArray"
      ]
    }
  ]
}
```


DEBUG Output
```
graphql-server_1         | Fri, 20 Jan 2017 23:37:14 GMT postgraphql:postgres begin
graphql-server_1         | Fri, 20 Jan 2017 23:37:14 GMT postgraphql:postgres select to_json("public"."numeric_array"(array[($1 + 0), ($2 + 0)])) as value
graphql-server_1         | Fri, 20 Jan 2017 23:37:14 GMT postgraphql:postgres error: invalid input syntax for integer: "123.1"
graphql-server_1         |     at Connection.parseE (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:554:11)
graphql-server_1         |     at Connection.parseMessage (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:381:17)
graphql-server_1         |     at Socket.<anonymous> (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:117:22)
graphql-server_1         |     at emitOne (events.js:96:13)
graphql-server_1         |     at Socket.emit (events.js:188:7)
graphql-server_1         |     at readableAddChunk (_stream_readable.js:176:18)
graphql-server_1         |     at Socket.Readable.push (_stream_readable.js:134:10)
graphql-server_1         |     at TCP.onread (net.js:551:20)
graphql-server_1         | Fri, 20 Jan 2017 23:37:14 GMT postgraphql:postgres commit
graphql-server_1         | 1 error(s) in 20.94ms :: mutation { numericArray(input: {_timestamp: [123.1, 456]}) { string } }
```

**Comment by angelosarto** [comment]
Oh, and a quick post as a workaround in case someone needs one:

If you need an array that is not an int or  text - declare your function to accept TEXT arrays instead and unnest and cast like this:

```
CREATE OR REPLACE FUNCTION your_function_that_needs_arrays(
  these_are_normal INTEGER[],
  this_is_also_fine TEXT[],
  these_are_really_timestamp TEXT[],
  these_are_really_numeric TEXT[]
) RETURNS something
AS $$

-- Outside of this select you can get new_values._normals, _fines, _timestamps, _numerics as a table  You could also could use aggregate to bring the rows back to arrays...
       SELECT
         t._normals,
         t._fines,
         t._timestamps:: TIMESTAMP,
         t._numerics::NUMERIC
       FROM unnest(these_are_normal, this_is_also_fine, these_are_really_timestamp, these_are_really_numeric)
         AS t(_ _normals, _fines, _timestamps, _numerics)
     ) as new_values

$$ LANGUAGE SQL VOLATILE;
```

**Comment by calebmer** [comment]
Ok cool. It looks like my proposed solution should fix this case then. I’d be happy to merge a PR which explicitly casts inputs 😊

**Comment by benjie** [comment]
Thanks for the great test case @angelosarto; can confirm this is fixed in v4 👍
