### ISSUE TITLE
Error on query table with a hstore type field

### ISSUE THREAD

**Issue by anibalaguirreconsultora** [graphile/postgraphile#571]
I am getting the error `Expected string. Not 'object'` when doing a simple query on table that has an hstore type field

```
query {
  allItems  {
    edges {
      node {
        itemNo
        description
      }
    }
  }
}
```
```
{
  "errors": [
    {
      "message": "Expected string. Not 'object'.",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ],
      "path": [
        "allItems"
      ]
    }
  ],
  "data": {
    "allItems": null
  }
}
```
```
 _id           | uuid              | not null default uuid_generate_v4()
 item_no       | character varying |
 description   | text              |
 attr_values   | hstore            |
 categoryid    | uuid              |
```

**Comment by benjie** [comment]
I'm not sure we have explicit support for hstore yet; which version of PostGraphQL are you running?

There's an issue for this for v4 here:

https://github.com/graphile/graphile-build/issues/4

Which references #311.

In v4 this support can be added via a plugin.

**Comment by benjie** [comment]
(The plugin does not yet exist, to be clear.)

**Comment by anibalaguirreconsultora** [comment]
running version 3.5.0
error stack below

```
$ postgraphql --version                                                                                           
3.5.0                      
```
```
{
  "errors": [
    {
      "message": "Expected string. Not 'object'.",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ],
      "path": [
        "allItems"
      ],
      "stack": "Error: Expected string. Not 'object'.\n    at Object.transformPgValueIntoValue (/home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/build/postgres/inventory/type/scalar/pgStringType.js:12:19)\n    at PgNullableType.transformPgValueIntoValue (/home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/build/postgres/inventory/type/PgNullableType.js:31:58)\n    at /home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/build/postgres/inventory/type/PgClassType.js:60:43\n    at Array.map (native)\n    at PgClassType.transformPgValueIntoValue (/home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/build/postgres/inventory/type/PgClassType.js:58:48)\n    at /home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/build/postgres/inventory/paginator/PgPaginatorOrderingAttributes.js:71:67\n    at Array.map (native)\n    at PgPaginatorOrderingAttributes.<anonymous> (/home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/build/postgres/inventory/paginator/PgPaginatorOrderingAttributes.js:68:39)\n    at step (/home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:122:27)\n    at Object.next (/home/nodespeed/.nvm/versions/node/v6.10.2/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:103:57)"
    }
  ],
  "data": {
    "allItems": null
  }
}
```

**Comment by benjie** [comment]
I believe we simply do not have hstore support - a pull request adding it would be welcome (but you'd be better off adding it to v4 via a plugin: `npm install -g postgraphql@next`; see #506

**Comment by benjie** [comment]
v4.0.0-rc4 will contain hstore support
