### ISSUE TITLE
How to connect using unix domain socket?

### ISSUE THREAD

**Issue by epeli** [graphile/postgraphile#600]
I can connect to my database with psql with

    psql postgresql:///mydb?host=/var/run/postgresql

But how can I do that with postgraphql?

Doing 

    postgraphql -c postgresql:///mydb?host=/var/run/postgresql

crashes with

```

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://:5432/mydb
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

error: password authentication failed for user "ubuntu"
    at Connection.parseE (/home/ubuntu/test/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/home/ubuntu/test/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/home/ubuntu/test/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)

```

**Comment by benjie** [comment]
I couldn't find any documentation on that; but the tests for `pg-connection-string` suggest you can try something like:

`socket:/var/run/postgresql?db=mydb`

See:

https://github.com/iceddev/pg-connection-string/blob/13687353c9ecc4b2ea736ee0784a6a158a40a951/test/parse.js#L41-L46

Please let me know how you get on; if it works we ought to add it to the docs.

**Comment by epeli** [comment]
Works! Thanks!
