### ISSUE TITLE
Postgraphile crashes when role doesn't have permissions to any columns

### ISSUE THREAD

**Issue by flux627** [graphile/postgraphile#698]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:
```
    "postgraphile": "^4.0.0-alpha2.33",
```

Minimal SQL file that can be loaded into a clean database:

```sql
REVOKE ALL ON SCHEMA my_schema FROM PUBLIC;

CREATE ROLE "visitor" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION;
GRANT USAGE ON SCHEMA my_schema TO visitor;

CREATE ROLE "authenticated_user" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION;
GRANT USAGE ON SCHEMA my_schema TO authenticated_user;

CREATE ROLE "internal_service" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION ENCRYPTED PASSWORD $pg1$password$pg1$;
GRANT USAGE ON SCHEMA my_schema TO internal_service;
GRANT CONNECT ON DATABASE my_database TO internal_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA my_schema
GRANT SELECT ON TABLES TO internal_service;
CREATE ROLE "postgraphile" WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION ENCRYPTED PASSWORD $pg1$password$pg1$;

GRANT USAGE ON SCHEMA my_schema TO postgraphile;
GRANT CONNECT ON DATABASE my_database TO postgraphile;

GRANT visitor to postgraphile;
GRANT authenticated_user to postgraphile;
GRANT internal_service to postgraphile;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
INSERT INTO "my_schema"."_pgmigrations" (name, run_on) VALUES ('1517527975868_install-extensions', NOW());COMMIT;

CREATE TABLE "accounts" (
  "_id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  "_created_at" timestamp DEFAULT current_timestamp NOT NULL,
  "name" text UNIQUE NOT NULL,
);

GRANT SELECT (_id,name) ON "my_schema"."accounts" TO authenticated_user;
```

Steps to reproduce:

Run the following query while using the "visitor" role:

```graphql
query {
  allAccounts {
    edges {
      node {
        name
      }
    }
  }
}
```

Current behavior:
```
TypeError: fields.forEach is not a function
    at pickPgError (/opt/myproject/node_modules/postgraphile/build/postgraphql/extendedFormatError.js:9:16)
    at Object.extendedFormatError (/opt/myproject/node_modules/postgraphile/build/postgraphql/extendedFormatError.js:28:60)
    at formatError (/opt/myproject/node_modules/postgraphile/build/postgraphql/http/createPostGraphQLHttpRequestHandler.js:75:35)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/opt/myproject/node_modules/postgraphile/build/postgraphql/http/createPostGraphQLHttpRequestHandler.js:398:55)
    at step (/opt/myproject/node_modules/tslib/tslib.js:133:27)
    at Object.next (/opt/myproject/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/opt/myproject/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Expected behavior:
It should raise a 403, with proper response object.

Let me know if this is my own error. Thanks

**Comment by benjie** [comment]
It looks like you may have passed through `extendedErrors` as something that's not an array of the error fields to make available on the errors. I'm guessing the boolean `true`? Check the documentation for extendedErrors here:

https://www.graphile.org/postgraphile/usage-library/

I'll add a check in the code to give a more helpful error message.

**Comment by benjie** [comment]
Ahhhh; actually I'm guessing it might have been a string because it had to have a `.length` property. Was it a comma separated list perchance? I'll look at adding a split function there 🙂

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/postgraphile/commit/5ab4c944fa7b45c2dc10e909365698033ab6b4d8

**Comment by flux627** [comment]
Never got back to replying to this- this was indeed the problem. Thanks Benjie

**Comment by benjie** [comment]
Thanks for confirming 👍
