### ISSUE TITLE
Lambda only supports Node 6.10

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#707]
PostGraphile beta only supports Node 8.6+.

This is a problem. I was hoping that you'd just be able to transpile PostGraphile to get lambda support (since I expect lambda instances would use a bundle file anyway to reduce startup files) but due to our `favicon.ico` and `index.html` for GraphiQL we have some issues in this regard.

I've started work on an example here:

https://github.com/graphile/postgraphile-lambda-example

It successfully builds a zip file (via `npm run bundle`) to upload to Lambda, and that bundle does export a handler:

```
npx node@6
> const b = require('./bundle')
undefined
> (node:12923) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/Users/resources/favicon.ico'
(node:12923) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, open '/Users/benjiegillam/Documents/graphiql/public/index.html'
⚠️ WARNING⚠️  You requested to use schema 'app_public'; however we couldn't find some of those! Missing schemas are: 'app_public'

> b.handler
[Function]
```

However when I attempt to run it via API Gateway I get:

```
Unable to import module 'bundle': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/bundle.js:1:188633)
at n (/var/task/bundle.js:1:220)
at Object.<anonymous> (/var/task/bundle.js:1:188677)
at n (/var/task/bundle.js:1:220)
at /var/task/bundle.js:1:641
at Object.<anonymous> (/var/task/bundle.js:1:652)
```

I've never used lambda before; any pointers would be welcome.

**Comment by thewillhuang** [comment]
Here are the files i used to get to where i was, i included node_modules of postgraphile. Got as far as the multiple copies of graphql error, pg-native binding errors, but end up with pg config error, passing in the string instaed of the pool also fails with the same error.

If I stop trying to bundle tho, it works which is why I'm thinking it might be way easier if you would support 6.10 until aws lambda switches over to 8, dx wise, you wouldn't even need to bother with bundling, simply excluding everything in node_modules and upload it to aws lambda and it would work, as it did before.

```
{ user: 'username',
  password: undefined,
  host: 'localhost',
  port: null,
  database: 'test' }
nodejs server starting at port: 3000
Error: You must provide a valid PG client configuration
```
`package.json`
```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "dist/main.js",
  "author": "William Huang <will.h86@gmail.com>",
  "license": "MIT",
  "dependencies": {
    "postgraphile": "^4.0.0-beta.2"
  },
  "scripts": {
    "start": "rm -fr dist && webpack --progress --mode=development --watch & yarn dev",
    "dev": "nodemon -e js,jsx,sql,json dist/main.js",
    "build": "yarn clean && yarn && webpack --progress --mode=production && yarn nuke && yarn --prod",
    "nuke": "rm -fr node_modules",
    "clean": "rm -fr dist",
    "stage": "yarn && up && up url -o",
    "prod": "yarn && up production && up url -o",
    "open": "up url -o",
    "logs": "up logs -f",
    "db:create": "createdb mass-consensus",
    "db:drop": "dropdb mass-consensus",
    "db:up": "db-migrate up",
    "db:r": "yarn db:down && yarn db:up",
    "db:down": "db-migrate down",
    "db:reset": "db-migrate reset"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-ramda": "^1.4.3",
    "babel-plugin-transform-async-to-bluebird": "^1.1.1",
    "babel-plugin-transform-promise-to-bluebird": "^1.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "compression": "^1.7.2",
    "db-migrate": "^0.10.5",
    "db-migrate-pg": "^0.3.1",
    "eslint": "^4.18.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.6.1",
    "express": "^4.16.2",
    "lodash": "^4.17.5",
    "morgan": "^1.9.0",
    "nodemon": "^1.15.1",
    "ramda": "^0.25.0",
    "webpack": "^4.0.0",
    "webpack-cli": "^2.0.6"
  },
  "resolutions": {
    "graphql": "0.13.0"
  }
}

```
`webpack.config.js`
```js
const config = {
  target: 'node',

  node: { __dirname: true },

  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
        },
      },
    ],
  },

  externals: ['pg-native'],

};

module.exports = config;
```
`.babelrc`
```babelrc
{
  "presets": [
    ["env", {
      "targets": {
        "node": "6.10"
      }
    }],
    "stage-0"
  ],
  "plugins": [
    "ramda",
    "lodash",
    "transform-async-to-bluebird",
    "transform-promise-to-bluebird",
    ["transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true
    }]
  ]
}

```
`app.js`
```js
import express from 'express';
import { postgraphile } from 'postgraphile';
import morgan from 'morgan';
import compression from 'compression';
import Pool from 'pg-pool';
import url from 'url';

const app = express();
const {
  PORT = 3000,
  NODE_ENV = 'development',
  POSTGRES_CONNECTION = 'postgresql://user@localhost/test',
} = process.env;
const params = url.parse(process.env.DATABASE_URL || POSTGRES_CONNECTION);
const auth = params.auth.split(':');
const config = {
  user: auth[0],
  password: auth[1],
  host: params.hostname,
  port: params.port,
  database: params.pathname.split('/')[1],
};
console.log(config);
const pool = new Pool(config);
const isProduction = NODE_ENV !== 'development';

if (!isProduction) {
  app.use(morgan('dev'));
}
app.use(compression());
app.use(postgraphile(
  pool,
  ['test_pub'], {
    dynamicJson: true,
    graphiql: true,
    disableQueryLog: isProduction,
    graphqlRoute: '/',
    extendedErrors: ['hint', 'detail', 'errcode'],
    jwtSecret: 'lawls',
    jwtPgTypeIdentifier: 'test_pub.jwt_token',
    pgDefaultRole: 'person_anonymous',
    legacyRelations: 'omit',
  },
));

console.log(`nodejs server starting at port: ${PORT}`);
app.listen(PORT);

```

**Comment by thewillhuang** [comment]
```
devtool: 'eval',
```

makes pg config error go away ¯\_(ツ)_/¯

**Comment by thewillhuang** [comment]
what was causing the pg error was default uglifyjs which had function name and class name mangling below is the working webpack config.

a potential solution to the asset files is just to bundle them into one html file

```js
const webpack = require('webpack');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')

const config = {
  target: 'node',

  node: {
    __dirname: true,
    __filename: true,
  },

  mode: 'production',


  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          keep_fnames: true,
          keep_classnames: true,
        },
      }),
		]
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
        },
      },
    ],
  },

  plugins: [
    new webpack.IgnorePlugin(/\.\/native/, /\/pg\//),
  ]

};

module.exports = config;

```

**Comment by benjie** [comment]
@thewillhuang Have you tried running postgraphile on Lambda with `up` - it looks like you can use the `proxy` command to run a Node 8 manually until Lambda gets native Node8 support.

**Comment by thewillhuang** [comment]
yep, thats another solution! im just glad i got it working heh had to dig deep into webpack

**Comment by gardner** [comment]
AWS Lambda now supports "Node.js – v8.10, 4.3.2 and 6.10.3" https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by benjie** [comment]
👍 Google Cloud Functions are still stuck on 6, but now Lambda have upgraded it doesn’t seem worth worrying about 😊

**Comment by benjie** [comment]
Here's a basic working example using the postgraphile middleware and aws-serverless-express compatibility later

https://github.com/graphile/postgraphile-lambda-example

It's almost completely untested. It won't support GraphiQL.

**Comment by lskrajny** [comment]
Good example, was able to ran Postgraphile behind API Gateway!

Are there any chances to enable also GraphiQL ?

**Comment by brennongs** [comment]
@lskrajny Were you able to just plug and play? I'm running into all sorts of cors errors.
