### ISSUE TITLE
Define default orderBy column 

### ISSUE THREAD

**Issue by saerdnaer** [graphile/postgraphile#764]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [x] question 

Some developers using our GraphQL API complained that they always have to specify with which order a sub entity is sorted.

Would it make sense to add a smart comment onto the order field or the table, which defines a default orderBy column including [ASC | DESC]?

**Comment by benjie** [comment]
Totally; that'd be a great use of them. Would love a PR to this file: https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgConnectionArgOrderByDefaultValue.js

**Comment by benjie** [comment]
[semi-automated message] Hi, there has been no activity in this issue for over 8 weeks so I'm closing it to keep the issues/pull request manageable. If this is still an issue, please re-open with a comment explaining why.

![](https://media.giphy.com/media/RpNA43Cnd38Bi/giphy.gif?response_id=5925dc27fd5ebd80cc843ee9)

**Comment by saerdnaer** [comment]
@benjie Is there already a solution for the feature request?

**Comment by benjie** [comment]
You can write a plugin to apply a default before https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build-pg/src/plugins/PgConnectionArgOrderByDefaultValue.js kicks in.

**Comment by saerdnaer** [comment]
When I try to do this via https://gist.github.com/saerdnaer/6f47606cd736fa23d96008dc073029ec, I get following error. How can I disable the default hook?

```
Error: A naming conflict has occurred - two entities have tried to define the same key 'defaultValue'.

  The first entity was:

    Adding defaultValue to orderBy for field 'audioBinaries' of 'Query'

  The second entity was:

    Adding defaultValue PRIMARY_KEY_ASC to orderBy for field 'audioBinaries' of 'Query'
    at Object.extend (…/graphile-build/src/extend.js:33:13)
    at hook (/Users/hubela/Projekte/audiothek/at-graphile/src/plugins/DefaultOrderPlugin.ts:39:18)
    at SchemaBuilder.applyHooks (…/graphile-build/src/SchemaBuilder.js:411:20)
    at fieldWithHooks (…/graphile-build/src/makeNewBuild.js:644:33)
    at makeField (…/graphile-build-pg/src/plugins/PgAllRows.js:83:31)
    at reduce (…/graphile-build-pg/src/plugins/PgAllRows.js:219:13)
    at Array.reduce (<anonymous>) 
 ```

**Comment by saerdnaer** [comment]
Ah, adding following to the postgraphile options fixed the issue for me:
```
skipPlugins: [
	PgConnectionArgOrderByDefaultValue
],
```
