### ISSUE TITLE
Postgraphile command not working because of syntax error

### ISSUE THREAD

**Issue by briank1916** [graphile/postgraphile#795]
Hello, I am trying to set up postgraphile but I keep getting a syntax error any time I try to use the postgraphile command. Currently using node.js version 6.14.3. 
Error is below: 

/usr/lib/node_modules/postgraphile/build/postgraphile/cli.js:275
    (async () => {
           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by benjie** [comment]
PostGraphile only supports Node.js above v8.6; to see more requirements, view the requirements page:

https://www.graphile.org/postgraphile/requirements/

Node v8 is the current Node.js LTS; v6 is [no longer in active LTS](https://github.com/nodejs/Release), you should move to a newer Node.js versions if possible.

If you need to support Node.js below v8.6 then you can use babel and webpack to compile your application including the relevant node_modules to support older versions of JavaScript.
