### ISSUE TITLE
Error when an accessible function uses an inaccessible type

### ISSUE THREAD

**Issue by csnover** [graphile/postgraphile#812]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.0.0-rc.1.4

In Postgres, I tried to write a function which returned a record from a view. I granted the correct permissions on the *function*, so it was accessible to Postgraphile, but I failed to grant the correct permissions on the *view*, so the function’s return type was not visible.

```sql
CREATE VIEW foo AS SELECT 1 AS id, 2 as count;
-- ⚠️ Missing: GRANT SELECT ON foo TO postgraphile;

CREATE FUNCTION get_foo(id integer) RETURNS foo AS $$
  SELECT * FROM foo WHERE foo.id = get_foo.id;
$$ LANGUAGE SQL STABLE;
GRANT EXECUTE ON FUNCTION get_foo TO postgraphile;
```

As a result, when Postgraphile did type introspection, it couldn’t complete the return type for the function, and this error was raised when introspection of the function was performed (by e.g. loading graphiql):

```
Error: Type Foo must define one or more fields.
    at assertValidSchema (node_modules/graphql/type/validate.js:78:11)
    at Object.validate (node_modules/graphql/validation/validate.js:61:35)
    at parseQuery (node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:217:48)
    at Promise.all.paramsList.map (node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:482:63)
    at Array.map (<anonymous>)
    at requestHandler (node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:448:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

In `psql`, executing the function in this broken permissions state results in an appropriate “permission denied for relation foo” error. I would expect Postgraphile to report a similar error, instead of the current error which is rather cryptic and resulted in a lot of head-scratching on my end.

Thank you for your hard work on Postgraphile! I’m enjoying experimenting with it so far.

**Comment by benjie** [comment]
Please update to RC2 and/or set “ignoreRBAC: true”. I’m aware of this issue and hope to have a fix soon. Thanks for reporting 👍

**Comment by benjie** [comment]
This should be fixed in RC3 (available now)
