### ISSUE TITLE
"Error: Type 'TestsOrderBy' has already been registered!" on startup

### ISSUE THREAD

**Issue by jasongilman** [graphile/postgraphile#821]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

4.0.0-rc.2

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

postgraphile -c postgres://XXXX:XXXX@localhost:XXXX/XXXX

Current behavior:

```
PostGraphile server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5454/apostgre01
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

Error: Type 'TestsOrderBy' has already been registered!
    at Object.newWithHooks (/Users/user/work/project/node_modules/graphile-build/node8plus/makeNewBuild.js:511:17)
    at introspectionResultsByKind.class.filter.filter.forEach.table (/Users/user/work/project/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:25:7)
    at Array.forEach (<anonymous>)
    at PgConnectionArgOrderBy.builder.hook (/Users/user/work/project/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:22:134)
    at SchemaBuilder.applyHooks (/Users/user/work/project/node_modules/graphile-build/node8plus/SchemaBuilder.js:145:20)
    at SchemaBuilder.createBuild (/Users/user/work/project/node_modules/graphile-build/node8plus/SchemaBuilder.js:183:10)
    at SchemaBuilder.buildSchema (/Users/user/work/project/node_modules/graphile-build/node8plus/SchemaBuilder.js:189:26)
    at Object.exports.createPostGraphileSchema (/Users/user/work/project/node_modules/postgraphile-core/node8plus/index.js:223:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Expected behavior:

This is the first time I'm running postgraphile so I'm not sure what to expect other than it to start running.

**Comment by sjmcdowall** [comment]
Can you try rc.3 by using @next  ?? 

Not sure it will help, but it's the latest code ..

**Comment by benjie** [comment]
This most likely means that two different things are trying to have the same name. Do you have, for example, a table/view called `test` and another table/view called `tests`?

**Comment by benjie** [comment]
If you can share a minimal SQL file that can be loaded into a clean database then we can most likely point out what's causing the issue. Adding instrumentation for this to track where these conflicts come from is on my TODO list, but I suspect it's going to take a while to implement.

**Comment by jasongilman** [comment]
I tried version 3 earlier today and it caused the same problem. I did find that in one of the schemas there is a table called "TEST" and another one called "test". I don't control the database so I can't get rid of those. Is there a way to work around the problem?

**Comment by benjie** [comment]
Another way is to rename one table with a database comment using smart comments (see docs); but if that’s not an option then you can add a plugin that overrides the inflector - see recent discussion in our gitter chat.

**Comment by benjie** [comment]
[semi-automated message] To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.
