### ISSUE TITLE
Cannot run docker example

### ISSUE THREAD

**Issue by jmls** [graphile/postgraphile#847]
* [ x] bug report

PostGraphile version: v4.0.0-rc.4

Steps to reproduce:
running the sample code for docker
`sudo docker run -p 5000:5000 graphile/postgraphile --connection postgres://<user>:<password>@<pghost>/<db> --watch`

Current behavior:
container stops with the error

```
Error: Type 'BaselineCondition' has already been registered!
    at Object.newWithHooks (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/makeNewBuild.js:519:17)
    at introspectionResultsByKind.class.filter.filter.forEach.table (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgCondition.js:21:7)
    at Array.forEach (<anonymous>)
    at PgConnectionArgCondition.builder.hook (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgCondition.js:18:135)
    at SchemaBuilder.applyHooks (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:147:20)
    at SchemaBuilder.createBuild (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:185:10)
    at SchemaBuilder.buildSchema (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:191:26)
    at SchemaBuilder.watchSchema (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:231:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
Expected behavior:
the container to start running ;)

**Comment by benjie** [comment]
Looks like you have more than one thing in your database called baseline/baselines/baseline_condition/baseline_conditions; you can use smart comments to rename one of them to avoid the clash.

**Comment by benjie** [comment]
Closing this as have massively improved these kinds of errors in the next release: https://github.com/graphile/graphile-build/pull/292
