### ISSUE TITLE
GraphQLError: Schema is not configured for subscriptions

### ISSUE THREAD

**Issue by sfiros2003** [graphile/postgraphile#875]
Why getting this error? But everything seems as working.

1 error(s) in 160.33ms :: subscription { readPayload }
GraphQLError: Schema is not configured for subscriptions
    at getOperationRootType (/usr/local/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:270:15)
    at executeOperation (/usr/local/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:228:14)
    at executeImpl (/usr/local/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:136:26)
    at Object.execute (/usr/local/lib/node_modules/postgraphql/node_modules/graphql/execution/execute.js:113:150)
    at /usr/local/lib/node_modules/postgraphql/build/postgraphql/http/createPostGraphQLHttpRequestHandler.js:349:46
    at /usr/local/lib/node_modules/postgraphql/build/postgraphql/withPostGraphQLContext.js:62:42
    at step (/usr/local/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:122:27)
    at Object.next (/usr/local/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:103:57)
    at fulfilled (/usr/local/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:93:62)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by sfiros2003** [comment]
@benjie 
Thank you, it was an issue with the db switching. Tried to connect to the db which won't connect without the vpn connection.
