### ISSUE TITLE
Improve configuration message returned by --simple-collections flag with invalid argument

### ISSUE THREAD

**Issue by benjamin-rood** [graphile/postgraphile#881]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: 4.0.1

#### Current behavior:

```
postgraphile -c postgres://<host>/<database> --simple-collections
Error: Invalid configuration for simple collections: true
    at getPostGraphileBuilder (/Users/br/.nvm/versions/node/v9.4.0/lib/node_modules/postgraphile/node_modules/postgraphile-core/node8plus/index.js:75:15)
    at Object.exports.createPostGraphileSchema (/Users/br/.nvm/versions/node/v9.4.0/lib/node_modules/postgraphile/node_modules/postgraphile-core/node8plus/index.js:177:27)
    at createGqlSchema (/Users/br/.nvm/versions/node/v9.4.0/lib/node_modules/postgraphile/build/postgraphile/postgraphile.js:58:55)
    at getPostgraphileSchemaBuilder (/Users/br/.nvm/versions/node/v9.4.0/lib/node_modules/postgraphile/build/postgraphile/postgraphile.js:39:30)
    at Object.postgraphile [as default] (/Users/br/.nvm/versions/node/v9.4.0/lib/node_modules/postgraphile/build/postgraphile/postgraphile.js:116:53)
    at Object.<anonymous> (/Users/br/.nvm/versions/node/v9.4.0/lib/node_modules/postgraphile/build/postgraphile/cli.js:329:53)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

#### Suggested behavior:

Firstly, return the usage string as shown in the `--help` printout:
```
postgraphile -c postgres://<host>/<database> --simple-collections
Error: Invalid configuration for simple collections: true
Usage: --simple-collections [omit|both|only]      "omit" (default) - relay connections only, "only" - simple collections only (no Relay connections), "both" - both
```

~~~Secondly, I would suggest that the default value for `--simple-collections` be either "both" or "only" (i.e. enable the functionality) as that seems a natural POSIX behaviour.~~~

**Comment by benjie** [comment]
`--simple-collections` is deliberately opt-in only because GraphQL best practices recommend using cursor pagination, so we want to guide you along that path if we can.

**Comment by benjamin-rood** [comment]
@benjie Cool. I would like to do this myself.

**Comment by benjie** [comment]
Awesome 👏 I suspect the easiest way is to follow the similar error message here:

https://github.com/graphile/postgraphile/blob/master/src/postgraphile/cli.ts#L397

You can use `./scripts/dev -- --help` (The double hyphen is important) to run the build in development mode. Hit me up on chat if you need more guidance.

**Comment by benjie** [comment]
@benjamin-rood Any update on this?

**Comment by benjamin-rood** [comment]
Ah! Sorry! Will work on it tonight or tomorrow.

**Comment by benjie** [comment]
Awesome; thanks @benjamin-rood 👍

**Comment by benjie** [comment]
The link above is out of date; here’s an updated one. Can’t figure out how to permalink it on mobile :(

https://github.com/graphile/postgraphile/blob/master/src/postgraphile/cli.ts#L431

**Comment by benjamin-rood** [comment]
Haha, thanks. I actually put my Sherlock Holmes hat on and deduced that already ;)

**Comment by benjamin-rood** [comment]
Hey @benjie Yes, I will hit you up in discord. Been in "holiday mode" until this week, need to understand how to compile postgraphile-core to check if the fix is right.

**Comment by benjie** [comment]
Topical; see #core-development as @enisdenjo is currently working on core too.
