### ISSUE TITLE
Postgraphile hangs express from closing

### ISSUE THREAD

**Issue by itaied246** [graphile/postgraphile#912]
I'm submitting a 

* [ x ] bug report
* [ x ] question

PostGraphile version:
Library: 4.0.1

I have designed my http server (`express`) to have `start` and `stop` functions for testing purposes.

```js

export class Server {
  constructor(auth, port, dbUrl, schema) {
    this.port = port;
    this.server = express();
    this.server.get('/health', (req, res) => res.end());
    this.server.use(
      postgraphile(dbUrl, schema, {
        graphiql: true,
        pgSettings: createRole(auth),
      }),
    );
  }

  async start() {
    return new Promise((resolve, reject) => {
      this.server = this.server.listen(this.port, err => {
        if (err) reject(err);
        else resolve();
      });
    });
  }

  stop() {
    return new Promise((resolve, reject) =>
      this.server.close(err => {
        if (err) reject(err);
        else resolve();
      }),
    );
  }
}
```
This design is good for testing, since I can start and stop the server (and other components as well)
at the end of a test suite.

When I run a test that start the server, `jest` hang for 10 seconds after the test finishes.
If I comment out the `server.use(postgraphile(...))` then the test exit immediately.
Is there something that `postgraphile` do in the background that hold the `server`?
I guess it is probably something that have to do with an open connection.

Moreover, the `filterPlugin` make `jest` throw the following after the tests finished:

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at PostGraphileConnectionFilterPlugin (node_modules/postgraphile-plugin-connection-filter/index.js:7:3)
      at Object.<anonymous>.exports.getBuilder (node_modules/graphile-build/node8plus/index.js:83:11)
TypeError: require(...) is not a function
    at PostGraphileConnectionFilterPlugin (/dev/node_modules/postgraphile-plugin-connection-filter/index.js:7:48)
    at Object.plugin [as getBuilder] (/dev/node_modules/graphile-build/src/index.js:60:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  ●  process.exit called with "1"

      at handleFatalError (node_modules/postgraphile/build/postgraphile/postgraphile.js:123:13)
      at createGqlSchema (node_modules/postgraphile/build/postgraphile/postgraphile.js:65:20)
```

**Comment by benjie** [comment]
Instead of passing a connection string as the first parameter, pass a pgPool instance. Then when you want to close it down, call pgPool.end()

https://www.graphile.org/postgraphile/testing-jest/
