### ISSUE TITLE
Errors from Postgres creates UnresolvedPromises when using node middleware

### ISSUE THREAD

**Issue by bfelbo** [graphile/postgraphile#950]
I'm submitting a ... 

* [x] bug report (with known solution)
* [ ] feature request
* [ ] question 

Seen with node middleware for Postgraphile version 4.0, 4.1 and 4.2.

**Current behavior:**

If an error is thrown by Postgres such as the one by the following function, it creates an UnresolvedPromise with no response to the client.

plpgsql function:
```
create function reproduce_error() returns boolean as $$
begin
  raise exception 'Testing';
end;
$$ language plpgsql stable;
```

GraphQL query:
```
query {
  reproduceError
}
```

Node stack trace:
```
  Dec 29th 11:34:56pm ERRO (node:92192) UnhandledPromiseRejectionWarning: error: Testing
  Dec 29th 11:34:56pm ERRO     at Connection.parseE (/Users/.../node_modules/pg/lib/connection.js:539:11)
  Dec 29th 11:34:56pm ERRO     at Connection.parseMessage (/Users/.../node_modules/pg/lib/connection.js:366:17)
  Dec 29th 11:34:56pm ERRO     at Socket.<anonymous> (/Users/.../node_modules/pg/lib/connection.js:105:22)
  Dec 29th 11:34:56pm ERRO     at Socket.emit (events.js:182:13)
  Dec 29th 11:34:56pm ERRO     at Socket.EventEmitter.emit (domain.js:442:20)
  Dec 29th 11:34:56pm ERRO     at addChunk (_stream_readable.js:283:12)
  Dec 29th 11:34:56pm ERRO     at readableAddChunk (_stream_readable.js:264:11)
  Dec 29th 11:34:56pm ERRO     at Socket.Readable.push (_stream_readable.js:219:10)
  Dec 29th 11:34:56pm ERRO     at TCP.onread (net.js:639:20)
  Dec 29th 11:34:56pm ERRO (node:92192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  Dec 29th 11:34:56pm ERRO (node:92192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior:**

Error catching by Postgraphile without an UnresolvedPromise and a response to the client along the lines of this:

```
{
  "errors": [
    {
      "message": "Testing",
      "locations": [
        {
          "line": 71,
          "column": 3
        }
      ],
      "path": [
        "reproduceError"
      ]
    }
  ],
  "data": {
    "reproduceError": null
  }
}
```

**Solution:**

This issue was due to an unmet dependency for pg by Postgraphile. It can be solved by running `npm install --save pg` or equivalent for yarn. Hopefully this'll save others the trouble I had of debugging this to find the underlying issue.

**Comment by bfelbo** [comment]
This issue was due to an unmet dependency for pg by Postgraphile. It can be solved by running npm install --save pg or equivalent for yarn. Hopefully this'll save others the trouble I had of debugging to find the underlying issue.
