### ISSUE TITLE
error: operator is not unique: smallint[] @> smallint[] only when starting via NPM script

### ISSUE THREAD

**Issue by patsimon** [graphile/postgraphile#957]
I'm submitting a ... 

* [ x] bug report

PostGraphile version: 4.0.1

Minimal SQL file that can be loaded into a clean database:

```sql
sorry.. the sql I have to create the schema is not minimal
```

Steps to reproduce:

When I run the following command on the command line... the servers starts up fine

`postgraphile -c postgres://username:password@pellefant.db.elephantsql.com:5432/dbname -a -j -o`

When I run the exact same command from within an npm start script in my package.json file - it falls over with the below exception

```
A fatal error occurred when building the initial schema, so the process will now exit. Error details:

error: operator is not unique: smallint[] @> smallint[]
    at Connection.parseE (/Users/simoin/workspace/tenderpro/tenderpro_graphql_server/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/simoin/workspace/tenderpro/tenderpro_graphql_server/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/Users/simoin/workspace/tenderpro/tenderpro_graphql_server/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

The end goal here is to run a graphine server in EC2 and using an npm script appears to be the easier way to do this.

The odd thing is, if I connect to my localhost, it all works via CLI and the npm start script....

**Comment by benjie** [comment]
You’re running 4.2.0 via the npm script; my guess is you have 4.2.0 installed locally but 4.0.1 globally, hence the different behaviour. What version of postgres are you running? This looks like it might be an introspection query issue.
