### ISSUE TITLE
on delete mutation with classicalIds: No values were deleted in collection

### ISSUE THREAD

**Issue by srghma** [graphile/postgraphile#982]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: this bug is currently on master

_________________

query

```
mutation deleteProjectMutation(
  $input: DeleteProjectInput!
) {
  deleteProject(input: $input) {
    clientMutationId
    deletedProjectId
  }
}
```

input 

```
{"input": { "clientMutationId": "jrkpwsd7",
"id": "WyJwcm9qZWN0cyIsImYyMWY5NGM1LTVlZDItNDc2Mi04NGI3LTBjNzlmNjAxODJkNSJd" } }
```

returns error

```
{
  "errors": [
    {
      "extensions": {
        "exception": {}
      },
      "message": "No values were deleted in collection 'projects' because no values were found.",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "deleteProject"
      ],
      "stack": "Error: No values were deleted in collection 'projects' because no values were found.\n    at commonCodeRenameMe (/app/node_modules/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js:163:23)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    }
  ],
  "data": {
    "deleteProject": null
  }
}
```
________________

I have reproduced it here https://github.com/srghma/postgraphile/commits/master

```
    [ GraphQLError {
        message:
         'No values were deleted in collection \'posts\' because no values were found.',
        locations: [ { line: 4, column: 3 } ],
        path: [ 'c' ] },
      GraphQLError {
        message:
         'No values were deleted in collection \'posts\' because no values were found.',
        locations: [ { line: 8, column: 3 } ],
        path: [ 'g' ] } ] undefined
```

I can't fix it so I hand it to you @benjie

**Comment by srghma** [comment]
thank you for help, I'll check RLS once again

**Comment by benjie** [comment]
Ah sorry, for some reason your previous message didn't come through on GitHub until now :)
